from __future__ import annotations

from .handwritten import draw_list_method_bindings, object_properties, script_friendly_global_declarations
from .model import FunctionBinding
from .type_mapper import is_available_enum_value
from .policy import HEADER


def emit_stub(ctx, functions: list[FunctionBinding]) -> str:
    out = [
        HEADER,
        "// BML generated ImGui AngelScript API reference stub.\n",
        "// Advanced frame-scope API: call from render callbacks only.\n",
        "// This file is generated by tools/asgen/asgen.py.\n\n",
        "class CKTexture;\n\n",
        "class ImVec2 {\n",
        "  float x;\n",
        "  float y;\n",
        "  ImVec2();\n",
        "  ImVec2(float x, float y);\n",
        "}\n\n",
        "class ImVec3 {\n",
        "  float x;\n",
        "  float y;\n",
        "  float z;\n",
        "  ImVec3();\n",
        "  ImVec3(float x, float y, float z);\n",
        "}\n\n",
        "class ImVec4 {\n",
        "  float x;\n",
        "  float y;\n",
        "  float z;\n",
        "  float w;\n",
        "  ImVec4();\n",
        "  ImVec4(float x, float y, float z, float w);\n",
        "}\n\n",
    ]
    for name, fields in [
        ("ImGuiInt2", ["x", "y"]),
        ("ImGuiInt3", ["x", "y", "z"]),
        ("ImGuiInt4", ["x", "y", "z", "w"]),
    ]:
        args = ", ".join(f"int {field}" for field in fields)
        out.append(f"class {name} {{\n")
        for field in fields:
            out.append(f"  int {field};\n")
        out.append(f"  {name}();\n")
        out.append(f"  {name}({args});\n")
        out.append("}\n\n")

    for enum_name in sorted(ctx.used_enums):
        values = ctx.enum_groups.get(enum_name)
        if not values:
            continue
        out.append(f"enum {enum_name} {{\n")
        entries = []
        for value in values[1]:
            name = value.get("name")
            if not name or not is_available_enum_value(enum_name, str(name)):
                continue
            calc_value = value.get("calc_value")
            if not isinstance(calc_value, int) or calc_value < -2147483648 or calc_value > 2147483647:
                continue
            entries.append(f"  {name} = {calc_value}")
        out.append(",\n".join(entries))
        if entries:
            out.append("\n")
        out.append("}\n\n")

    properties = object_properties()
    for type_name in sorted(ctx.opaque_handle_types):
        out.append(f"class {type_name} {{\n")
        for as_type, field, _ in properties.get(type_name, []):
            out.append(f"  {as_type} get_{field}() property;\n")
        if type_name == "ImDrawList":
            for binding in draw_list_method_bindings():
                out.append(f"  {binding.declaration};\n")
        out.append("}\n\n")

    out.append("namespace ImGui {\n")
    seen: set[str] = set()
    for decl in script_friendly_global_declarations():
        if decl in seen:
            continue
        seen.add(decl)
        out.append(f"  {decl};\n")
    for fn in functions:
        if fn.script_decl in seen:
            continue
        seen.add(fn.script_decl)
        out.append(f"  {fn.script_decl};\n")
    out.append("}\n")
    return "".join(out)
