from __future__ import annotations

from dataclasses import dataclass
from typing import Any

HEADER = """// This file is generated by tools/asgen/asgen.py. Do not edit by hand.
"""


SKIP_FUNCTIONS = {
    "CreateContext",
    "DestroyContext",
    "GetCurrentContext",
    "SetCurrentContext",
    "NewFrame",
    "EndFrame",
    "Render",
    "TextUnformatted",
    "CalcTextSize",
    "Image",
    "ImageButton",
    "ImageWithBg",
    "GetStyleColorVec4",
    "SliderScalar",
    "DragScalar",
    "InputScalar",
    "ColorPicker4",
    "SetDragDropPayload",
    "AcceptDragDropPayload",
}

HAND_WRITTEN_CIMGUI_SYMBOLS = {
    "igTextUnformatted",
    "igCalcTextSize",
    "igImage",
    "igImageButton",
    "igImageWithBg",
    "igGetStyleColorVec4",
    "igSliderScalar",
    "igDragScalar",
    "igInputScalar",
    "igColorPicker4",
    "igSetDragDropPayload",
    "igAcceptDragDropPayload",
}

UNSAFE_PUBLIC_FUNCTIONS = {
    "DestroyPlatformWindows",
    "RenderPlatformWindowsDefault",
    "UpdatePlatformWindows",
}

BML_UNAVAILABLE_FUNCTIONS = {
    "DockSpace",
    "DockSpaceOverViewport",
    "FindViewportByID",
    "FindViewportByPlatformHandle",
    "GetBackgroundDrawList",
    "GetForegroundDrawList",
    "GetWindowDockID",
    "GetWindowDpiScale",
    "GetWindowViewport",
    "IsWindowDocked",
    "SetNextWindowClass",
    "SetNextWindowDockID",
    "SetNextWindowViewport",
}

BML_UNAVAILABLE_TYPES = {
    "ImGuiDockNodeFlags",
    "ImGuiWindowClass",
}

BML_UNAVAILABLE_ENUM_VALUE_FRAGMENTS = {
    "Dock",
    "Docking",
    "Viewports",
    "HasMouseHoveredViewport",
    "HasParentViewport",
}

BML_AVAILABLE_VIEWPORT_FLAGS = {
    "ImGuiViewportFlags_None",
    "ImGuiViewportFlags_IsPlatformWindow",
    "ImGuiViewportFlags_IsPlatformMonitor",
    "ImGuiViewportFlags_OwnedByApp",
}

FRAME_INDEPENDENT_FUNCTIONS = {
    "ColorConvertFloat4ToU32",
    "ColorConvertHSVtoRGB",
    "ColorConvertRGBtoHSV",
    "ColorConvertU32ToFloat4",
    "GetVersion",
}

ADDRESS_OF_RETURN_FUNCTIONS = {
    "GetIO",
    "GetStyle",
}

BORROWED_HANDLE_RETURNS = {
    "ImDrawList",
    "ImFont",
    "ImGuiIO",
    "ImGuiStorage",
    "ImGuiStyle",
    "ImGuiViewport",
}


@dataclass(frozen=True)
class SurfaceDecision:
    symbol: str
    reason: str | None = None

    @property
    def allowed(self) -> bool:
        return self.reason is None


class SurfacePolicy:
    def classify(self, item: dict[str, Any]) -> SurfaceDecision:
        funcname = str(item.get("funcname", ""))
        cimguiname = str(item.get("cimguiname", ""))
        location = str(item.get("location", ""))
        namespace = str(item.get("namespace", ""))

        if namespace != "ImGui":
            return SurfaceDecision(cimguiname, "non-Imgui namespace")
        if location.startswith("imgui_internal"):
            return SurfaceDecision(cimguiname, "imgui_internal")
        if item.get("templated"):
            return SurfaceDecision(cimguiname, "templated")
        if "..." in str(item.get("args", "")):
            return SurfaceDecision(cimguiname, "varargs")
        if funcname in UNSAFE_PUBLIC_FUNCTIONS:
            return SurfaceDecision(cimguiname, "platform lifecycle is owned by BML")
        if funcname in BML_UNAVAILABLE_FUNCTIONS:
            return SurfaceDecision(cimguiname, "not available in BML's compiled ImGui surface")
        signature_text = f"{item.get('ret', '')} {item.get('args', '')}"
        if any(type_name in signature_text for type_name in BML_UNAVAILABLE_TYPES):
            return SurfaceDecision(cimguiname, "not available in BML's compiled ImGui surface")
        if "Debug" in funcname:
            return SurfaceDecision(cimguiname, "debug tooling is not part of BML ImGui script surface")
        if funcname in SKIP_FUNCTIONS:
            reason = "hand-written overload" if cimguiname in HAND_WRITTEN_CIMGUI_SYMBOLS else "context/frame lifecycle is owned by BML"
            return SurfaceDecision(cimguiname, reason)
        return SurfaceDecision(cimguiname)
