// This file is generated by tools/asgen/asgen.py. Do not edit by hand.
// BML generated ImGui AngelScript API reference stub.
// Advanced frame-scope API: call from render callbacks only.
// This file is generated by tools/asgen/asgen.py.

class CKTexture;

class ImVec2 {
  float x;
  float y;
  ImVec2();
  ImVec2(float x, float y);
}

class ImVec3 {
  float x;
  float y;
  float z;
  ImVec3();
  ImVec3(float x, float y, float z);
}

class ImVec4 {
  float x;
  float y;
  float z;
  float w;
  ImVec4();
  ImVec4(float x, float y, float z, float w);
}

class ImGuiInt2 {
  int x;
  int y;
  ImGuiInt2();
  ImGuiInt2(int x, int y);
}

class ImGuiInt3 {
  int x;
  int y;
  int z;
  ImGuiInt3();
  ImGuiInt3(int x, int y, int z);
}

class ImGuiInt4 {
  int x;
  int y;
  int z;
  int w;
  ImGuiInt4();
  ImGuiInt4(int x, int y, int z, int w);
}

enum ImDrawFlags {
  ImDrawFlags_None = 0,
  ImDrawFlags_Closed = 1,
  ImDrawFlags_RoundCornersTopLeft = 16,
  ImDrawFlags_RoundCornersTopRight = 32,
  ImDrawFlags_RoundCornersBottomLeft = 64,
  ImDrawFlags_RoundCornersBottomRight = 128,
  ImDrawFlags_RoundCornersNone = 256,
  ImDrawFlags_RoundCornersTop = 48,
  ImDrawFlags_RoundCornersBottom = 192,
  ImDrawFlags_RoundCornersLeft = 80,
  ImDrawFlags_RoundCornersRight = 160,
  ImDrawFlags_RoundCornersAll = 240,
  ImDrawFlags_RoundCornersDefault_ = 240,
  ImDrawFlags_RoundCornersMask_ = 496
}

enum ImDrawListFlags {
  ImDrawListFlags_None = 0,
  ImDrawListFlags_AntiAliasedLines = 1,
  ImDrawListFlags_AntiAliasedLinesUseTex = 2,
  ImDrawListFlags_AntiAliasedFill = 4,
  ImDrawListFlags_AllowVtxOffset = 8
}

enum ImFontFlags {
  ImFontFlags_None = 0,
  ImFontFlags_NoLoadError = 2,
  ImFontFlags_NoLoadGlyphs = 4,
  ImFontFlags_LockBakedSizes = 8
}

enum ImGuiBackendFlags {
  ImGuiBackendFlags_None = 0,
  ImGuiBackendFlags_HasGamepad = 1,
  ImGuiBackendFlags_HasMouseCursors = 2,
  ImGuiBackendFlags_HasSetMousePos = 4,
  ImGuiBackendFlags_RendererHasVtxOffset = 8,
  ImGuiBackendFlags_RendererHasTextures = 16
}

enum ImGuiButtonFlags {
  ImGuiButtonFlags_None = 0,
  ImGuiButtonFlags_MouseButtonLeft = 1,
  ImGuiButtonFlags_MouseButtonRight = 2,
  ImGuiButtonFlags_MouseButtonMiddle = 4,
  ImGuiButtonFlags_MouseButtonMask_ = 7,
  ImGuiButtonFlags_EnableNav = 8
}

enum ImGuiChildFlags {
  ImGuiChildFlags_None = 0,
  ImGuiChildFlags_Borders = 1,
  ImGuiChildFlags_AlwaysUseWindowPadding = 2,
  ImGuiChildFlags_ResizeX = 4,
  ImGuiChildFlags_ResizeY = 8,
  ImGuiChildFlags_AutoResizeX = 16,
  ImGuiChildFlags_AutoResizeY = 32,
  ImGuiChildFlags_AlwaysAutoResize = 64,
  ImGuiChildFlags_FrameStyle = 128,
  ImGuiChildFlags_NavFlattened = 256
}

enum ImGuiCol {
  ImGuiCol_Text = 0,
  ImGuiCol_TextDisabled = 1,
  ImGuiCol_WindowBg = 2,
  ImGuiCol_ChildBg = 3,
  ImGuiCol_PopupBg = 4,
  ImGuiCol_Border = 5,
  ImGuiCol_BorderShadow = 6,
  ImGuiCol_FrameBg = 7,
  ImGuiCol_FrameBgHovered = 8,
  ImGuiCol_FrameBgActive = 9,
  ImGuiCol_TitleBg = 10,
  ImGuiCol_TitleBgActive = 11,
  ImGuiCol_TitleBgCollapsed = 12,
  ImGuiCol_MenuBarBg = 13,
  ImGuiCol_ScrollbarBg = 14,
  ImGuiCol_ScrollbarGrab = 15,
  ImGuiCol_ScrollbarGrabHovered = 16,
  ImGuiCol_ScrollbarGrabActive = 17,
  ImGuiCol_CheckMark = 18,
  ImGuiCol_SliderGrab = 19,
  ImGuiCol_SliderGrabActive = 20,
  ImGuiCol_Button = 21,
  ImGuiCol_ButtonHovered = 22,
  ImGuiCol_ButtonActive = 23,
  ImGuiCol_Header = 24,
  ImGuiCol_HeaderHovered = 25,
  ImGuiCol_HeaderActive = 26,
  ImGuiCol_Separator = 27,
  ImGuiCol_SeparatorHovered = 28,
  ImGuiCol_SeparatorActive = 29,
  ImGuiCol_ResizeGrip = 30,
  ImGuiCol_ResizeGripHovered = 31,
  ImGuiCol_ResizeGripActive = 32,
  ImGuiCol_InputTextCursor = 33,
  ImGuiCol_TabHovered = 34,
  ImGuiCol_Tab = 35,
  ImGuiCol_TabSelected = 36,
  ImGuiCol_TabSelectedOverline = 37,
  ImGuiCol_TabDimmed = 38,
  ImGuiCol_TabDimmedSelected = 39,
  ImGuiCol_TabDimmedSelectedOverline = 40,
  ImGuiCol_PlotLines = 43,
  ImGuiCol_PlotLinesHovered = 44,
  ImGuiCol_PlotHistogram = 45,
  ImGuiCol_PlotHistogramHovered = 46,
  ImGuiCol_TableHeaderBg = 47,
  ImGuiCol_TableBorderStrong = 48,
  ImGuiCol_TableBorderLight = 49,
  ImGuiCol_TableRowBg = 50,
  ImGuiCol_TableRowBgAlt = 51,
  ImGuiCol_TextLink = 52,
  ImGuiCol_TextSelectedBg = 53,
  ImGuiCol_TreeLines = 54,
  ImGuiCol_DragDropTarget = 55,
  ImGuiCol_DragDropTargetBg = 56,
  ImGuiCol_UnsavedMarker = 57,
  ImGuiCol_NavCursor = 58,
  ImGuiCol_NavWindowingHighlight = 59,
  ImGuiCol_NavWindowingDimBg = 60,
  ImGuiCol_ModalWindowDimBg = 61,
  ImGuiCol_COUNT = 62
}

enum ImGuiColorEditFlags {
  ImGuiColorEditFlags_None = 0,
  ImGuiColorEditFlags_NoAlpha = 2,
  ImGuiColorEditFlags_NoPicker = 4,
  ImGuiColorEditFlags_NoOptions = 8,
  ImGuiColorEditFlags_NoSmallPreview = 16,
  ImGuiColorEditFlags_NoInputs = 32,
  ImGuiColorEditFlags_NoTooltip = 64,
  ImGuiColorEditFlags_NoLabel = 128,
  ImGuiColorEditFlags_NoSidePreview = 256,
  ImGuiColorEditFlags_NoDragDrop = 512,
  ImGuiColorEditFlags_NoBorder = 1024,
  ImGuiColorEditFlags_NoColorMarkers = 2048,
  ImGuiColorEditFlags_AlphaOpaque = 4096,
  ImGuiColorEditFlags_AlphaNoBg = 8192,
  ImGuiColorEditFlags_AlphaPreviewHalf = 16384,
  ImGuiColorEditFlags_AlphaBar = 262144,
  ImGuiColorEditFlags_HDR = 524288,
  ImGuiColorEditFlags_DisplayRGB = 1048576,
  ImGuiColorEditFlags_DisplayHSV = 2097152,
  ImGuiColorEditFlags_DisplayHex = 4194304,
  ImGuiColorEditFlags_Uint8 = 8388608,
  ImGuiColorEditFlags_Float = 16777216,
  ImGuiColorEditFlags_PickerHueBar = 33554432,
  ImGuiColorEditFlags_PickerHueWheel = 67108864,
  ImGuiColorEditFlags_InputRGB = 134217728,
  ImGuiColorEditFlags_InputHSV = 268435456,
  ImGuiColorEditFlags_DefaultOptions_ = 177209344,
  ImGuiColorEditFlags_AlphaMask_ = 28674,
  ImGuiColorEditFlags_DisplayMask_ = 7340032,
  ImGuiColorEditFlags_DataTypeMask_ = 25165824,
  ImGuiColorEditFlags_PickerMask_ = 100663296,
  ImGuiColorEditFlags_InputMask_ = 402653184
}

enum ImGuiComboFlags {
  ImGuiComboFlags_None = 0,
  ImGuiComboFlags_PopupAlignLeft = 1,
  ImGuiComboFlags_HeightSmall = 2,
  ImGuiComboFlags_HeightRegular = 4,
  ImGuiComboFlags_HeightLarge = 8,
  ImGuiComboFlags_HeightLargest = 16,
  ImGuiComboFlags_NoArrowButton = 32,
  ImGuiComboFlags_NoPreview = 64,
  ImGuiComboFlags_WidthFitPreview = 128,
  ImGuiComboFlags_HeightMask_ = 30
}

enum ImGuiCond {
  ImGuiCond_None = 0,
  ImGuiCond_Always = 1,
  ImGuiCond_Once = 2,
  ImGuiCond_FirstUseEver = 4,
  ImGuiCond_Appearing = 8
}

enum ImGuiConfigFlags {
  ImGuiConfigFlags_None = 0,
  ImGuiConfigFlags_NavEnableKeyboard = 1,
  ImGuiConfigFlags_NavEnableGamepad = 2,
  ImGuiConfigFlags_NoMouse = 16,
  ImGuiConfigFlags_NoMouseCursorChange = 32,
  ImGuiConfigFlags_NoKeyboard = 64,
  ImGuiConfigFlags_IsSRGB = 1048576,
  ImGuiConfigFlags_IsTouchScreen = 2097152
}

enum ImGuiDataType {
  ImGuiDataType_S8 = 0,
  ImGuiDataType_U8 = 1,
  ImGuiDataType_S16 = 2,
  ImGuiDataType_U16 = 3,
  ImGuiDataType_S32 = 4,
  ImGuiDataType_U32 = 5,
  ImGuiDataType_S64 = 6,
  ImGuiDataType_U64 = 7,
  ImGuiDataType_Float = 8,
  ImGuiDataType_Double = 9,
  ImGuiDataType_Bool = 10,
  ImGuiDataType_String = 11,
  ImGuiDataType_COUNT = 12
}

enum ImGuiDir {
  ImGuiDir_None = -1,
  ImGuiDir_Left = 0,
  ImGuiDir_Right = 1,
  ImGuiDir_Up = 2,
  ImGuiDir_Down = 3,
  ImGuiDir_COUNT = 4
}

enum ImGuiDragDropFlags {
  ImGuiDragDropFlags_None = 0,
  ImGuiDragDropFlags_SourceNoPreviewTooltip = 1,
  ImGuiDragDropFlags_SourceNoDisableHover = 2,
  ImGuiDragDropFlags_SourceNoHoldToOpenOthers = 4,
  ImGuiDragDropFlags_SourceAllowNullID = 8,
  ImGuiDragDropFlags_SourceExtern = 16,
  ImGuiDragDropFlags_PayloadAutoExpire = 32,
  ImGuiDragDropFlags_PayloadNoCrossContext = 64,
  ImGuiDragDropFlags_PayloadNoCrossProcess = 128,
  ImGuiDragDropFlags_AcceptBeforeDelivery = 1024,
  ImGuiDragDropFlags_AcceptNoDrawDefaultRect = 2048,
  ImGuiDragDropFlags_AcceptNoPreviewTooltip = 4096,
  ImGuiDragDropFlags_AcceptDrawAsHovered = 8192,
  ImGuiDragDropFlags_AcceptPeekOnly = 3072
}

enum ImGuiFocusedFlags {
  ImGuiFocusedFlags_None = 0,
  ImGuiFocusedFlags_ChildWindows = 1,
  ImGuiFocusedFlags_RootWindow = 2,
  ImGuiFocusedFlags_AnyWindow = 4,
  ImGuiFocusedFlags_NoPopupHierarchy = 8,
  ImGuiFocusedFlags_RootAndChildWindows = 3
}

enum ImGuiHoveredFlags {
  ImGuiHoveredFlags_None = 0,
  ImGuiHoveredFlags_ChildWindows = 1,
  ImGuiHoveredFlags_RootWindow = 2,
  ImGuiHoveredFlags_AnyWindow = 4,
  ImGuiHoveredFlags_NoPopupHierarchy = 8,
  ImGuiHoveredFlags_AllowWhenBlockedByPopup = 32,
  ImGuiHoveredFlags_AllowWhenBlockedByActiveItem = 128,
  ImGuiHoveredFlags_AllowWhenOverlappedByItem = 256,
  ImGuiHoveredFlags_AllowWhenOverlappedByWindow = 512,
  ImGuiHoveredFlags_AllowWhenDisabled = 1024,
  ImGuiHoveredFlags_NoNavOverride = 2048,
  ImGuiHoveredFlags_AllowWhenOverlapped = 768,
  ImGuiHoveredFlags_RectOnly = 928,
  ImGuiHoveredFlags_RootAndChildWindows = 3,
  ImGuiHoveredFlags_ForTooltip = 4096,
  ImGuiHoveredFlags_Stationary = 8192,
  ImGuiHoveredFlags_DelayNone = 16384,
  ImGuiHoveredFlags_DelayShort = 32768,
  ImGuiHoveredFlags_DelayNormal = 65536,
  ImGuiHoveredFlags_NoSharedDelay = 131072
}

enum ImGuiInputFlags {
  ImGuiInputFlags_None = 0,
  ImGuiInputFlags_Repeat = 1,
  ImGuiInputFlags_RouteActive = 1024,
  ImGuiInputFlags_RouteFocused = 2048,
  ImGuiInputFlags_RouteGlobal = 4096,
  ImGuiInputFlags_RouteAlways = 8192,
  ImGuiInputFlags_RouteOverFocused = 16384,
  ImGuiInputFlags_RouteOverActive = 32768,
  ImGuiInputFlags_RouteUnlessBgFocused = 65536,
  ImGuiInputFlags_RouteFromRootWindow = 131072,
  ImGuiInputFlags_Tooltip = 262144
}

enum ImGuiInputTextFlags {
  ImGuiInputTextFlags_None = 0,
  ImGuiInputTextFlags_CharsDecimal = 1,
  ImGuiInputTextFlags_CharsHexadecimal = 2,
  ImGuiInputTextFlags_CharsScientific = 4,
  ImGuiInputTextFlags_CharsUppercase = 8,
  ImGuiInputTextFlags_CharsNoBlank = 16,
  ImGuiInputTextFlags_AllowTabInput = 32,
  ImGuiInputTextFlags_EnterReturnsTrue = 64,
  ImGuiInputTextFlags_EscapeClearsAll = 128,
  ImGuiInputTextFlags_CtrlEnterForNewLine = 256,
  ImGuiInputTextFlags_ReadOnly = 512,
  ImGuiInputTextFlags_Password = 1024,
  ImGuiInputTextFlags_AlwaysOverwrite = 2048,
  ImGuiInputTextFlags_AutoSelectAll = 4096,
  ImGuiInputTextFlags_ParseEmptyRefVal = 8192,
  ImGuiInputTextFlags_DisplayEmptyRefVal = 16384,
  ImGuiInputTextFlags_NoHorizontalScroll = 32768,
  ImGuiInputTextFlags_NoUndoRedo = 65536,
  ImGuiInputTextFlags_ElideLeft = 131072,
  ImGuiInputTextFlags_CallbackCompletion = 262144,
  ImGuiInputTextFlags_CallbackHistory = 524288,
  ImGuiInputTextFlags_CallbackAlways = 1048576,
  ImGuiInputTextFlags_CallbackCharFilter = 2097152,
  ImGuiInputTextFlags_CallbackResize = 4194304,
  ImGuiInputTextFlags_CallbackEdit = 8388608,
  ImGuiInputTextFlags_WordWrap = 16777216
}

enum ImGuiItemFlags {
  ImGuiItemFlags_None = 0,
  ImGuiItemFlags_NoTabStop = 1,
  ImGuiItemFlags_NoNav = 2,
  ImGuiItemFlags_NoNavDefaultFocus = 4,
  ImGuiItemFlags_ButtonRepeat = 8,
  ImGuiItemFlags_AutoClosePopups = 16,
  ImGuiItemFlags_AllowDuplicateId = 32,
  ImGuiItemFlags_Disabled = 64
}

enum ImGuiKey {
  ImGuiKey_None = 0,
  ImGuiKey_NamedKey_BEGIN = 512,
  ImGuiKey_Tab = 512,
  ImGuiKey_LeftArrow = 513,
  ImGuiKey_RightArrow = 514,
  ImGuiKey_UpArrow = 515,
  ImGuiKey_DownArrow = 516,
  ImGuiKey_PageUp = 517,
  ImGuiKey_PageDown = 518,
  ImGuiKey_Home = 519,
  ImGuiKey_End = 520,
  ImGuiKey_Insert = 521,
  ImGuiKey_Delete = 522,
  ImGuiKey_Backspace = 523,
  ImGuiKey_Space = 524,
  ImGuiKey_Enter = 525,
  ImGuiKey_Escape = 526,
  ImGuiKey_LeftCtrl = 527,
  ImGuiKey_LeftShift = 528,
  ImGuiKey_LeftAlt = 529,
  ImGuiKey_LeftSuper = 530,
  ImGuiKey_RightCtrl = 531,
  ImGuiKey_RightShift = 532,
  ImGuiKey_RightAlt = 533,
  ImGuiKey_RightSuper = 534,
  ImGuiKey_Menu = 535,
  ImGuiKey_0 = 536,
  ImGuiKey_1 = 537,
  ImGuiKey_2 = 538,
  ImGuiKey_3 = 539,
  ImGuiKey_4 = 540,
  ImGuiKey_5 = 541,
  ImGuiKey_6 = 542,
  ImGuiKey_7 = 543,
  ImGuiKey_8 = 544,
  ImGuiKey_9 = 545,
  ImGuiKey_A = 546,
  ImGuiKey_B = 547,
  ImGuiKey_C = 548,
  ImGuiKey_D = 549,
  ImGuiKey_E = 550,
  ImGuiKey_F = 551,
  ImGuiKey_G = 552,
  ImGuiKey_H = 553,
  ImGuiKey_I = 554,
  ImGuiKey_J = 555,
  ImGuiKey_K = 556,
  ImGuiKey_L = 557,
  ImGuiKey_M = 558,
  ImGuiKey_N = 559,
  ImGuiKey_O = 560,
  ImGuiKey_P = 561,
  ImGuiKey_Q = 562,
  ImGuiKey_R = 563,
  ImGuiKey_S = 564,
  ImGuiKey_T = 565,
  ImGuiKey_U = 566,
  ImGuiKey_V = 567,
  ImGuiKey_W = 568,
  ImGuiKey_X = 569,
  ImGuiKey_Y = 570,
  ImGuiKey_Z = 571,
  ImGuiKey_F1 = 572,
  ImGuiKey_F2 = 573,
  ImGuiKey_F3 = 574,
  ImGuiKey_F4 = 575,
  ImGuiKey_F5 = 576,
  ImGuiKey_F6 = 577,
  ImGuiKey_F7 = 578,
  ImGuiKey_F8 = 579,
  ImGuiKey_F9 = 580,
  ImGuiKey_F10 = 581,
  ImGuiKey_F11 = 582,
  ImGuiKey_F12 = 583,
  ImGuiKey_F13 = 584,
  ImGuiKey_F14 = 585,
  ImGuiKey_F15 = 586,
  ImGuiKey_F16 = 587,
  ImGuiKey_F17 = 588,
  ImGuiKey_F18 = 589,
  ImGuiKey_F19 = 590,
  ImGuiKey_F20 = 591,
  ImGuiKey_F21 = 592,
  ImGuiKey_F22 = 593,
  ImGuiKey_F23 = 594,
  ImGuiKey_F24 = 595,
  ImGuiKey_Apostrophe = 596,
  ImGuiKey_Comma = 597,
  ImGuiKey_Minus = 598,
  ImGuiKey_Period = 599,
  ImGuiKey_Slash = 600,
  ImGuiKey_Semicolon = 601,
  ImGuiKey_Equal = 602,
  ImGuiKey_LeftBracket = 603,
  ImGuiKey_Backslash = 604,
  ImGuiKey_RightBracket = 605,
  ImGuiKey_GraveAccent = 606,
  ImGuiKey_CapsLock = 607,
  ImGuiKey_ScrollLock = 608,
  ImGuiKey_NumLock = 609,
  ImGuiKey_PrintScreen = 610,
  ImGuiKey_Pause = 611,
  ImGuiKey_Keypad0 = 612,
  ImGuiKey_Keypad1 = 613,
  ImGuiKey_Keypad2 = 614,
  ImGuiKey_Keypad3 = 615,
  ImGuiKey_Keypad4 = 616,
  ImGuiKey_Keypad5 = 617,
  ImGuiKey_Keypad6 = 618,
  ImGuiKey_Keypad7 = 619,
  ImGuiKey_Keypad8 = 620,
  ImGuiKey_Keypad9 = 621,
  ImGuiKey_KeypadDecimal = 622,
  ImGuiKey_KeypadDivide = 623,
  ImGuiKey_KeypadMultiply = 624,
  ImGuiKey_KeypadSubtract = 625,
  ImGuiKey_KeypadAdd = 626,
  ImGuiKey_KeypadEnter = 627,
  ImGuiKey_KeypadEqual = 628,
  ImGuiKey_AppBack = 629,
  ImGuiKey_AppForward = 630,
  ImGuiKey_Oem102 = 631,
  ImGuiKey_GamepadStart = 632,
  ImGuiKey_GamepadBack = 633,
  ImGuiKey_GamepadFaceLeft = 634,
  ImGuiKey_GamepadFaceRight = 635,
  ImGuiKey_GamepadFaceUp = 636,
  ImGuiKey_GamepadFaceDown = 637,
  ImGuiKey_GamepadDpadLeft = 638,
  ImGuiKey_GamepadDpadRight = 639,
  ImGuiKey_GamepadDpadUp = 640,
  ImGuiKey_GamepadDpadDown = 641,
  ImGuiKey_GamepadL1 = 642,
  ImGuiKey_GamepadR1 = 643,
  ImGuiKey_GamepadL2 = 644,
  ImGuiKey_GamepadR2 = 645,
  ImGuiKey_GamepadL3 = 646,
  ImGuiKey_GamepadR3 = 647,
  ImGuiKey_GamepadLStickLeft = 648,
  ImGuiKey_GamepadLStickRight = 649,
  ImGuiKey_GamepadLStickUp = 650,
  ImGuiKey_GamepadLStickDown = 651,
  ImGuiKey_GamepadRStickLeft = 652,
  ImGuiKey_GamepadRStickRight = 653,
  ImGuiKey_GamepadRStickUp = 654,
  ImGuiKey_GamepadRStickDown = 655,
  ImGuiKey_MouseLeft = 656,
  ImGuiKey_MouseRight = 657,
  ImGuiKey_MouseMiddle = 658,
  ImGuiKey_MouseX1 = 659,
  ImGuiKey_MouseX2 = 660,
  ImGuiKey_MouseWheelX = 661,
  ImGuiKey_MouseWheelY = 662,
  ImGuiKey_ReservedForModCtrl = 663,
  ImGuiKey_ReservedForModShift = 664,
  ImGuiKey_ReservedForModAlt = 665,
  ImGuiKey_ReservedForModSuper = 666,
  ImGuiKey_NamedKey_END = 667,
  ImGuiKey_NamedKey_COUNT = 155,
  ImGuiMod_None = 0,
  ImGuiMod_Ctrl = 4096,
  ImGuiMod_Shift = 8192,
  ImGuiMod_Alt = 16384,
  ImGuiMod_Super = 32768,
  ImGuiMod_Mask_ = 61440
}

enum ImGuiMouseButton {
  ImGuiMouseButton_Left = 0,
  ImGuiMouseButton_Right = 1,
  ImGuiMouseButton_Middle = 2,
  ImGuiMouseButton_COUNT = 5
}

enum ImGuiMouseCursor {
  ImGuiMouseCursor_None = -1,
  ImGuiMouseCursor_Arrow = 0,
  ImGuiMouseCursor_TextInput = 1,
  ImGuiMouseCursor_ResizeAll = 2,
  ImGuiMouseCursor_ResizeNS = 3,
  ImGuiMouseCursor_ResizeEW = 4,
  ImGuiMouseCursor_ResizeNESW = 5,
  ImGuiMouseCursor_ResizeNWSE = 6,
  ImGuiMouseCursor_Hand = 7,
  ImGuiMouseCursor_Wait = 8,
  ImGuiMouseCursor_Progress = 9,
  ImGuiMouseCursor_NotAllowed = 10,
  ImGuiMouseCursor_COUNT = 11
}

enum ImGuiPopupFlags {
  ImGuiPopupFlags_None = 0,
  ImGuiPopupFlags_MouseButtonLeft = 4,
  ImGuiPopupFlags_MouseButtonRight = 8,
  ImGuiPopupFlags_MouseButtonMiddle = 12,
  ImGuiPopupFlags_NoReopen = 32,
  ImGuiPopupFlags_NoOpenOverExistingPopup = 128,
  ImGuiPopupFlags_NoOpenOverItems = 256,
  ImGuiPopupFlags_AnyPopupId = 1024,
  ImGuiPopupFlags_AnyPopupLevel = 2048,
  ImGuiPopupFlags_AnyPopup = 3072,
  ImGuiPopupFlags_MouseButtonShift_ = 2,
  ImGuiPopupFlags_MouseButtonMask_ = 12,
  ImGuiPopupFlags_InvalidMask_ = 3
}

enum ImGuiSelectableFlags {
  ImGuiSelectableFlags_None = 0,
  ImGuiSelectableFlags_NoAutoClosePopups = 1,
  ImGuiSelectableFlags_SpanAllColumns = 2,
  ImGuiSelectableFlags_AllowDoubleClick = 4,
  ImGuiSelectableFlags_Disabled = 8,
  ImGuiSelectableFlags_AllowOverlap = 16,
  ImGuiSelectableFlags_Highlight = 32,
  ImGuiSelectableFlags_SelectOnNav = 64
}

enum ImGuiSliderFlags {
  ImGuiSliderFlags_None = 0,
  ImGuiSliderFlags_Logarithmic = 32,
  ImGuiSliderFlags_NoRoundToFormat = 64,
  ImGuiSliderFlags_NoInput = 128,
  ImGuiSliderFlags_WrapAround = 256,
  ImGuiSliderFlags_ClampOnInput = 512,
  ImGuiSliderFlags_ClampZeroRange = 1024,
  ImGuiSliderFlags_NoSpeedTweaks = 2048,
  ImGuiSliderFlags_ColorMarkers = 4096,
  ImGuiSliderFlags_AlwaysClamp = 1536,
  ImGuiSliderFlags_InvalidMask_ = 1879048207
}

enum ImGuiStyleVar {
  ImGuiStyleVar_Alpha = 0,
  ImGuiStyleVar_DisabledAlpha = 1,
  ImGuiStyleVar_WindowPadding = 2,
  ImGuiStyleVar_WindowRounding = 3,
  ImGuiStyleVar_WindowBorderSize = 4,
  ImGuiStyleVar_WindowMinSize = 5,
  ImGuiStyleVar_WindowTitleAlign = 6,
  ImGuiStyleVar_ChildRounding = 7,
  ImGuiStyleVar_ChildBorderSize = 8,
  ImGuiStyleVar_PopupRounding = 9,
  ImGuiStyleVar_PopupBorderSize = 10,
  ImGuiStyleVar_FramePadding = 11,
  ImGuiStyleVar_FrameRounding = 12,
  ImGuiStyleVar_FrameBorderSize = 13,
  ImGuiStyleVar_ItemSpacing = 14,
  ImGuiStyleVar_ItemInnerSpacing = 15,
  ImGuiStyleVar_IndentSpacing = 16,
  ImGuiStyleVar_CellPadding = 17,
  ImGuiStyleVar_ScrollbarSize = 18,
  ImGuiStyleVar_ScrollbarRounding = 19,
  ImGuiStyleVar_ScrollbarPadding = 20,
  ImGuiStyleVar_GrabMinSize = 21,
  ImGuiStyleVar_GrabRounding = 22,
  ImGuiStyleVar_ImageRounding = 23,
  ImGuiStyleVar_ImageBorderSize = 24,
  ImGuiStyleVar_TabRounding = 25,
  ImGuiStyleVar_TabBorderSize = 26,
  ImGuiStyleVar_TabMinWidthBase = 27,
  ImGuiStyleVar_TabMinWidthShrink = 28,
  ImGuiStyleVar_TabBarBorderSize = 29,
  ImGuiStyleVar_TabBarOverlineSize = 30,
  ImGuiStyleVar_TableAngledHeadersAngle = 31,
  ImGuiStyleVar_TableAngledHeadersTextAlign = 32,
  ImGuiStyleVar_TreeLinesSize = 33,
  ImGuiStyleVar_TreeLinesRounding = 34,
  ImGuiStyleVar_ButtonTextAlign = 35,
  ImGuiStyleVar_SelectableTextAlign = 36,
  ImGuiStyleVar_SeparatorTextBorderSize = 37,
  ImGuiStyleVar_SeparatorTextAlign = 38,
  ImGuiStyleVar_SeparatorTextPadding = 39,
  ImGuiStyleVar_COUNT = 41
}

enum ImGuiTabBarFlags {
  ImGuiTabBarFlags_None = 0,
  ImGuiTabBarFlags_Reorderable = 1,
  ImGuiTabBarFlags_AutoSelectNewTabs = 2,
  ImGuiTabBarFlags_TabListPopupButton = 4,
  ImGuiTabBarFlags_NoCloseWithMiddleMouseButton = 8,
  ImGuiTabBarFlags_NoTabListScrollingButtons = 16,
  ImGuiTabBarFlags_NoTooltip = 32,
  ImGuiTabBarFlags_DrawSelectedOverline = 64,
  ImGuiTabBarFlags_FittingPolicyMixed = 128,
  ImGuiTabBarFlags_FittingPolicyShrink = 256,
  ImGuiTabBarFlags_FittingPolicyScroll = 512,
  ImGuiTabBarFlags_FittingPolicyMask_ = 896,
  ImGuiTabBarFlags_FittingPolicyDefault_ = 128
}

enum ImGuiTabItemFlags {
  ImGuiTabItemFlags_None = 0,
  ImGuiTabItemFlags_UnsavedDocument = 1,
  ImGuiTabItemFlags_SetSelected = 2,
  ImGuiTabItemFlags_NoCloseWithMiddleMouseButton = 4,
  ImGuiTabItemFlags_NoPushId = 8,
  ImGuiTabItemFlags_NoTooltip = 16,
  ImGuiTabItemFlags_NoReorder = 32,
  ImGuiTabItemFlags_Leading = 64,
  ImGuiTabItemFlags_Trailing = 128,
  ImGuiTabItemFlags_NoAssumedClosure = 256
}

enum ImGuiTableBgTarget {
  ImGuiTableBgTarget_None = 0,
  ImGuiTableBgTarget_RowBg0 = 1,
  ImGuiTableBgTarget_RowBg1 = 2,
  ImGuiTableBgTarget_CellBg = 3
}

enum ImGuiTableColumnFlags {
  ImGuiTableColumnFlags_None = 0,
  ImGuiTableColumnFlags_Disabled = 1,
  ImGuiTableColumnFlags_DefaultHide = 2,
  ImGuiTableColumnFlags_DefaultSort = 4,
  ImGuiTableColumnFlags_WidthStretch = 8,
  ImGuiTableColumnFlags_WidthFixed = 16,
  ImGuiTableColumnFlags_NoResize = 32,
  ImGuiTableColumnFlags_NoReorder = 64,
  ImGuiTableColumnFlags_NoHide = 128,
  ImGuiTableColumnFlags_NoClip = 256,
  ImGuiTableColumnFlags_NoSort = 512,
  ImGuiTableColumnFlags_NoSortAscending = 1024,
  ImGuiTableColumnFlags_NoSortDescending = 2048,
  ImGuiTableColumnFlags_NoHeaderLabel = 4096,
  ImGuiTableColumnFlags_NoHeaderWidth = 8192,
  ImGuiTableColumnFlags_PreferSortAscending = 16384,
  ImGuiTableColumnFlags_PreferSortDescending = 32768,
  ImGuiTableColumnFlags_IndentEnable = 65536,
  ImGuiTableColumnFlags_IndentDisable = 131072,
  ImGuiTableColumnFlags_AngledHeader = 262144,
  ImGuiTableColumnFlags_IsEnabled = 16777216,
  ImGuiTableColumnFlags_IsVisible = 33554432,
  ImGuiTableColumnFlags_IsSorted = 67108864,
  ImGuiTableColumnFlags_IsHovered = 134217728,
  ImGuiTableColumnFlags_WidthMask_ = 24,
  ImGuiTableColumnFlags_IndentMask_ = 196608,
  ImGuiTableColumnFlags_StatusMask_ = 251658240,
  ImGuiTableColumnFlags_NoDirectResize_ = 1073741824
}

enum ImGuiTableFlags {
  ImGuiTableFlags_None = 0,
  ImGuiTableFlags_Resizable = 1,
  ImGuiTableFlags_Reorderable = 2,
  ImGuiTableFlags_Hideable = 4,
  ImGuiTableFlags_Sortable = 8,
  ImGuiTableFlags_NoSavedSettings = 16,
  ImGuiTableFlags_ContextMenuInBody = 32,
  ImGuiTableFlags_RowBg = 64,
  ImGuiTableFlags_BordersInnerH = 128,
  ImGuiTableFlags_BordersOuterH = 256,
  ImGuiTableFlags_BordersInnerV = 512,
  ImGuiTableFlags_BordersOuterV = 1024,
  ImGuiTableFlags_BordersH = 384,
  ImGuiTableFlags_BordersV = 1536,
  ImGuiTableFlags_BordersInner = 640,
  ImGuiTableFlags_BordersOuter = 1280,
  ImGuiTableFlags_Borders = 1920,
  ImGuiTableFlags_NoBordersInBody = 2048,
  ImGuiTableFlags_NoBordersInBodyUntilResize = 4096,
  ImGuiTableFlags_SizingFixedFit = 8192,
  ImGuiTableFlags_SizingFixedSame = 16384,
  ImGuiTableFlags_SizingStretchProp = 24576,
  ImGuiTableFlags_SizingStretchSame = 32768,
  ImGuiTableFlags_NoHostExtendX = 65536,
  ImGuiTableFlags_NoHostExtendY = 131072,
  ImGuiTableFlags_NoKeepColumnsVisible = 262144,
  ImGuiTableFlags_PreciseWidths = 524288,
  ImGuiTableFlags_NoClip = 1048576,
  ImGuiTableFlags_PadOuterX = 2097152,
  ImGuiTableFlags_NoPadOuterX = 4194304,
  ImGuiTableFlags_NoPadInnerX = 8388608,
  ImGuiTableFlags_ScrollX = 16777216,
  ImGuiTableFlags_ScrollY = 33554432,
  ImGuiTableFlags_SortMulti = 67108864,
  ImGuiTableFlags_SortTristate = 134217728,
  ImGuiTableFlags_HighlightHoveredColumn = 268435456,
  ImGuiTableFlags_SizingMask_ = 57344
}

enum ImGuiTableRowFlags {
  ImGuiTableRowFlags_None = 0,
  ImGuiTableRowFlags_Headers = 1
}

enum ImGuiTreeNodeFlags {
  ImGuiTreeNodeFlags_None = 0,
  ImGuiTreeNodeFlags_Selected = 1,
  ImGuiTreeNodeFlags_Framed = 2,
  ImGuiTreeNodeFlags_AllowOverlap = 4,
  ImGuiTreeNodeFlags_NoTreePushOnOpen = 8,
  ImGuiTreeNodeFlags_NoAutoOpenOnLog = 16,
  ImGuiTreeNodeFlags_DefaultOpen = 32,
  ImGuiTreeNodeFlags_OpenOnDoubleClick = 64,
  ImGuiTreeNodeFlags_OpenOnArrow = 128,
  ImGuiTreeNodeFlags_Leaf = 256,
  ImGuiTreeNodeFlags_Bullet = 512,
  ImGuiTreeNodeFlags_FramePadding = 1024,
  ImGuiTreeNodeFlags_SpanAvailWidth = 2048,
  ImGuiTreeNodeFlags_SpanFullWidth = 4096,
  ImGuiTreeNodeFlags_SpanLabelWidth = 8192,
  ImGuiTreeNodeFlags_SpanAllColumns = 16384,
  ImGuiTreeNodeFlags_LabelSpanAllColumns = 32768,
  ImGuiTreeNodeFlags_NavLeftJumpsToParent = 131072,
  ImGuiTreeNodeFlags_CollapsingHeader = 26,
  ImGuiTreeNodeFlags_DrawLinesNone = 262144,
  ImGuiTreeNodeFlags_DrawLinesFull = 524288,
  ImGuiTreeNodeFlags_DrawLinesToNodes = 1048576
}

enum ImGuiViewportFlags {
  ImGuiViewportFlags_None = 0,
  ImGuiViewportFlags_IsPlatformWindow = 1,
  ImGuiViewportFlags_IsPlatformMonitor = 2,
  ImGuiViewportFlags_OwnedByApp = 4
}

enum ImGuiWindowFlags {
  ImGuiWindowFlags_None = 0,
  ImGuiWindowFlags_NoTitleBar = 1,
  ImGuiWindowFlags_NoResize = 2,
  ImGuiWindowFlags_NoMove = 4,
  ImGuiWindowFlags_NoScrollbar = 8,
  ImGuiWindowFlags_NoScrollWithMouse = 16,
  ImGuiWindowFlags_NoCollapse = 32,
  ImGuiWindowFlags_AlwaysAutoResize = 64,
  ImGuiWindowFlags_NoBackground = 128,
  ImGuiWindowFlags_NoSavedSettings = 256,
  ImGuiWindowFlags_NoMouseInputs = 512,
  ImGuiWindowFlags_MenuBar = 1024,
  ImGuiWindowFlags_HorizontalScrollbar = 2048,
  ImGuiWindowFlags_NoFocusOnAppearing = 4096,
  ImGuiWindowFlags_NoBringToFrontOnFocus = 8192,
  ImGuiWindowFlags_AlwaysVerticalScrollbar = 16384,
  ImGuiWindowFlags_AlwaysHorizontalScrollbar = 32768,
  ImGuiWindowFlags_NoNavInputs = 65536,
  ImGuiWindowFlags_NoNavFocus = 131072,
  ImGuiWindowFlags_UnsavedDocument = 262144,
  ImGuiWindowFlags_NoNav = 196608,
  ImGuiWindowFlags_NoDecoration = 43,
  ImGuiWindowFlags_NoInputs = 197120,
  ImGuiWindowFlags_ChildWindow = 16777216,
  ImGuiWindowFlags_Tooltip = 33554432,
  ImGuiWindowFlags_Popup = 67108864,
  ImGuiWindowFlags_Modal = 134217728,
  ImGuiWindowFlags_ChildMenu = 268435456
}

class ImDrawList {
  ImDrawListFlags get_Flags() property;
  void AddLine(const ImVec2 &in p1, const ImVec2 &in p2, uint col, float thickness = 1.0f);
  void AddRect(const ImVec2 &in p_min, const ImVec2 &in p_max, uint col, float rounding = 0.0f, ImDrawFlags flags = ImDrawFlags_None, float thickness = 1.0f);
  void AddRectFilled(const ImVec2 &in p_min, const ImVec2 &in p_max, uint col, float rounding = 0.0f, ImDrawFlags flags = ImDrawFlags_None);
  void AddCircle(const ImVec2 &in center, float radius, uint col, int num_segments = 0, float thickness = 1.0f);
  void AddCircleFilled(const ImVec2 &in center, float radius, uint col, int num_segments = 0);
  void AddTriangle(const ImVec2 &in p1, const ImVec2 &in p2, const ImVec2 &in p3, uint col, float thickness = 1.0f);
  void AddTriangleFilled(const ImVec2 &in p1, const ImVec2 &in p2, const ImVec2 &in p3, uint col);
  void AddQuad(const ImVec2 &in p1, const ImVec2 &in p2, const ImVec2 &in p3, const ImVec2 &in p4, uint col, float thickness = 1.0f);
  void AddQuadFilled(const ImVec2 &in p1, const ImVec2 &in p2, const ImVec2 &in p3, const ImVec2 &in p4, uint col);
  void AddBezierCubic(const ImVec2 &in p1, const ImVec2 &in p2, const ImVec2 &in p3, const ImVec2 &in p4, uint col, float thickness = 1.0f, int num_segments = 0);
  void AddBezierQuadratic(const ImVec2 &in p1, const ImVec2 &in p2, const ImVec2 &in p3, uint col, float thickness = 1.0f, int num_segments = 0);
  void AddNgon(const ImVec2 &in center, float radius, uint col, int num_segments, float thickness = 1.0f);
  void AddNgonFilled(const ImVec2 &in center, float radius, uint col, int num_segments);
  void AddPolyline4(const ImVec2 &in p1, const ImVec2 &in p2, const ImVec2 &in p3, const ImVec2 &in p4, uint col, ImDrawFlags flags = ImDrawFlags_None, float thickness = 1.0f);
  void AddText(const ImVec2 &in pos, uint col, const string &in text);
  void AddImage(CKTexture@ texture, const ImVec2 &in p_min, const ImVec2 &in p_max, const ImVec2 &in uv_min = ImVec2(0,0), const ImVec2 &in uv_max = ImVec2(1,1), uint col = 0xffffffff);
  void PathClear();
  void PathLineTo(const ImVec2 &in pos);
  void PathArcTo(const ImVec2 &in center, float radius, float a_min, float a_max, int num_segments = 0);
  void PathArcToFast(const ImVec2 &in center, float radius, int a_min_of_12, int a_max_of_12);
  void PathBezierCubicCurveTo(const ImVec2 &in p2, const ImVec2 &in p3, const ImVec2 &in p4, int num_segments = 0);
  void PathBezierQuadraticCurveTo(const ImVec2 &in p2, const ImVec2 &in p3, int num_segments = 0);
  void PathRect(const ImVec2 &in rect_min, const ImVec2 &in rect_max, float rounding = 0.0f, ImDrawFlags flags = ImDrawFlags_None);
  void PathFillConvex(uint col);
  void PathStroke(uint col, ImDrawFlags flags = ImDrawFlags_None, float thickness = 1.0f);
}

class ImFont {
  ImFontFlags get_Flags() property;
  float get_CurrentRasterizerDensity() property;
  uint get_FontId() property;
  float get_LegacySize() property;
  uint get_EllipsisChar() property;
  uint get_FallbackChar() property;
  bool get_EllipsisAutoBake() property;
}

class ImGuiIO {
  ImGuiConfigFlags get_ConfigFlags() property;
  ImGuiBackendFlags get_BackendFlags() property;
  ImVec2 get_DisplaySize() property;
  ImVec2 get_DisplayFramebufferScale() property;
  float get_DeltaTime() property;
  bool get_FontAllowUserScaling() property;
  bool get_MouseDrawCursor() property;
  float get_MouseDoubleClickTime() property;
  float get_MouseDoubleClickMaxDist() property;
  float get_MouseDragThreshold() property;
  float get_KeyRepeatDelay() property;
  float get_KeyRepeatRate() property;
  bool get_WantCaptureMouse() property;
  bool get_WantCaptureKeyboard() property;
  bool get_WantTextInput() property;
  bool get_WantSetMousePos() property;
  bool get_WantSaveIniSettings() property;
  bool get_NavActive() property;
  bool get_NavVisible() property;
  float get_Framerate() property;
  int get_MetricsRenderVertices() property;
  int get_MetricsRenderIndices() property;
  int get_MetricsRenderWindows() property;
  int get_MetricsActiveWindows() property;
  ImVec2 get_MouseDelta() property;
  ImVec2 get_MousePos() property;
  float get_MouseWheel() property;
}

class ImGuiStorage {
}

class ImGuiStyle {
  float get_Alpha() property;
  float get_DisabledAlpha() property;
  ImVec2 get_WindowPadding() property;
  float get_WindowRounding() property;
  float get_WindowBorderSize() property;
  ImVec2 get_WindowMinSize() property;
  ImVec2 get_WindowTitleAlign() property;
  ImGuiDir get_WindowMenuButtonPosition() property;
  float get_ChildRounding() property;
  float get_ChildBorderSize() property;
  float get_PopupRounding() property;
  float get_PopupBorderSize() property;
  ImVec2 get_FramePadding() property;
  float get_FrameRounding() property;
  float get_FrameBorderSize() property;
  ImVec2 get_ItemSpacing() property;
  ImVec2 get_ItemInnerSpacing() property;
  ImVec2 get_CellPadding() property;
  float get_IndentSpacing() property;
  float get_ScrollbarSize() property;
  float get_ScrollbarRounding() property;
  float get_GrabMinSize() property;
  float get_GrabRounding() property;
  float get_LogSliderDeadzone() property;
  float get_ImageRounding() property;
  float get_ImageBorderSize() property;
  float get_TabRounding() property;
  float get_TabBorderSize() property;
  ImGuiDir get_ColorButtonPosition() property;
  ImVec2 get_ButtonTextAlign() property;
  ImVec2 get_SelectableTextAlign() property;
  ImVec2 get_DisplayWindowPadding() property;
  ImVec2 get_DisplaySafeAreaPadding() property;
  float get_MouseCursorScale() property;
  bool get_AntiAliasedLines() property;
  bool get_AntiAliasedLinesUseTex() property;
  bool get_AntiAliasedFill() property;
  float get_CurveTessellationTol() property;
  float get_CircleTessellationMaxError() property;
}

class ImGuiViewport {
  uint get_ID() property;
  ImGuiViewportFlags get_Flags() property;
  ImVec2 get_Pos() property;
  ImVec2 get_Size() property;
  ImVec2 get_FramebufferScale() property;
  ImVec2 get_WorkPos() property;
  ImVec2 get_WorkSize() property;
}

namespace ImGui {
  bool Begin(const string &in name, ImGuiWindowFlags flags = ImGuiWindowFlags_None);
  ImVec2 CalcTextSize(const string &in text, bool hide_text_after_double_hash = false, float wrap_width = -1.0f);
  void TextUnformatted(const string &in text);
  void TextUnformattedRange(const string &in text, uint length);
  ImVec4 GetStyleColorVec4(ImGuiCol idx);
  bool SliderScalarFloat(const string &in label, float &inout v, float v_min, float v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragScalarFloat(const string &in label, float &inout v, float v_speed, float v_min, float v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool InputScalarFloat(const string &in label, float &inout v, float step, float step_fast, const string &in format = "", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool SliderScalarDouble(const string &in label, double &inout v, double v_min, double v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragScalarDouble(const string &in label, double &inout v, float v_speed, double v_min, double v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool InputScalarDouble(const string &in label, double &inout v, double step, double step_fast, const string &in format = "", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool SliderScalarInt(const string &in label, int &inout v, int v_min, int v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragScalarInt(const string &in label, int &inout v, float v_speed, int v_min, int v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool InputScalarInt(const string &in label, int &inout v, int step, int step_fast, const string &in format = "", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool SliderScalarUInt(const string &in label, uint &inout v, uint v_min, uint v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragScalarUInt(const string &in label, uint &inout v, float v_speed, uint v_min, uint v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool InputScalarUInt(const string &in label, uint &inout v, uint step, uint step_fast, const string &in format = "", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool SliderScalarInt64(const string &in label, int64 &inout v, int64 v_min, int64 v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragScalarInt64(const string &in label, int64 &inout v, float v_speed, int64 v_min, int64 v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool InputScalarInt64(const string &in label, int64 &inout v, int64 step, int64 step_fast, const string &in format = "", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool SliderScalarUInt64(const string &in label, uint64 &inout v, uint64 v_min, uint64 v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragScalarUInt64(const string &in label, uint64 &inout v, float v_speed, uint64 v_min, uint64 v_max, const string &in format = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool InputScalarUInt64(const string &in label, uint64 &inout v, uint64 step, uint64 step_fast, const string &in format = "", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool SetDragDropPayloadString(const string &in type, const string &in payload, ImGuiCond cond = ImGuiCond_None);
  bool AcceptDragDropPayloadString(const string &in type, string &out payload, ImGuiDragDropFlags flags = ImGuiDragDropFlags_None);
  bool ComboText(const string &in label, int &inout current_item, const string &in newline_separated_items, int popup_max_height_in_items = -1);
  bool ListBoxText(const string &in label, int &inout current_item, const string &in newline_separated_items, int height_in_items = -1);
  bool ColorPicker4(const string &in label, ImVec4 &inout col, ImGuiColorEditFlags flags = ImGuiColorEditFlags_None);
  void Image(CKTexture@ texture, const ImVec2 &in size, const ImVec2 &in uv0 = ImVec2(0,0), const ImVec2 &in uv1 = ImVec2(1,1));
  void ImageWithBg(CKTexture@ texture, const ImVec2 &in size, const ImVec2 &in uv0 = ImVec2(0,0), const ImVec2 &in uv1 = ImVec2(1,1), const ImVec4 &in bg_col = ImVec4(0,0,0,0), const ImVec4 &in tint_col = ImVec4(1,1,1,1));
  bool ImageButton(const string &in id, CKTexture@ texture, const ImVec2 &in size, const ImVec2 &in uv0 = ImVec2(0,0), const ImVec2 &in uv1 = ImVec2(1,1), const ImVec4 &in bg_col = ImVec4(0,0,0,0), const ImVec4 &in tint_col = ImVec4(1,1,1,1));
  ImDrawList@ GetBackgroundDrawList();
  ImDrawList@ GetForegroundDrawList();
  void AlignTextToFramePadding();
  bool ArrowButton(const string &in str_id, ImGuiDir dir);
  bool Begin(const string &in name, bool &inout p_open, ImGuiWindowFlags flags = ImGuiWindowFlags_None);
  bool BeginChild(const string &in str_id, const ImVec2 &in size = ImVec2(0,0), ImGuiChildFlags child_flags = ImGuiChildFlags_None, ImGuiWindowFlags window_flags = ImGuiWindowFlags_None);
  bool BeginChild(uint id, const ImVec2 &in size = ImVec2(0,0), ImGuiChildFlags child_flags = ImGuiChildFlags_None, ImGuiWindowFlags window_flags = ImGuiWindowFlags_None);
  bool BeginCombo(const string &in label, const string &in preview_value, ImGuiComboFlags flags = ImGuiComboFlags_None);
  void BeginDisabled(bool disabled = true);
  bool BeginDragDropSource(ImGuiDragDropFlags flags = ImGuiDragDropFlags_None);
  bool BeginDragDropTarget();
  void BeginGroup();
  bool BeginItemTooltip();
  bool BeginListBox(const string &in label, const ImVec2 &in size = ImVec2(0,0));
  bool BeginMainMenuBar();
  bool BeginMenu(const string &in label, bool enabled = true);
  bool BeginMenuBar();
  bool BeginPopup(const string &in str_id, ImGuiWindowFlags flags = ImGuiWindowFlags_None);
  bool BeginPopupContextItem(const string &in str_id = "", ImGuiPopupFlags popup_flags = ImGuiPopupFlags_None);
  bool BeginPopupContextVoid(const string &in str_id = "", ImGuiPopupFlags popup_flags = ImGuiPopupFlags_None);
  bool BeginPopupContextWindow(const string &in str_id = "", ImGuiPopupFlags popup_flags = ImGuiPopupFlags_None);
  bool BeginPopupModal(const string &in name, bool &inout p_open, ImGuiWindowFlags flags = ImGuiWindowFlags_None);
  bool BeginTabBar(const string &in str_id, ImGuiTabBarFlags flags = ImGuiTabBarFlags_None);
  bool BeginTabItem(const string &in label, bool &inout p_open, ImGuiTabItemFlags flags = ImGuiTabItemFlags_None);
  bool BeginTable(const string &in str_id, int columns, ImGuiTableFlags flags = ImGuiTableFlags_None, const ImVec2 &in outer_size = ImVec2(0.0f,0.0f), float inner_width = 0.0);
  bool BeginTooltip();
  void Bullet();
  bool Button(const string &in label, const ImVec2 &in size = ImVec2(0,0));
  float CalcItemWidth();
  bool Checkbox(const string &in label, bool &inout v);
  bool CheckboxFlags(const string &in label, int &inout flags, int flags_value);
  bool CheckboxFlags(const string &in label, uint &inout flags, uint flags_value);
  void CloseCurrentPopup();
  bool CollapsingHeader(const string &in label, ImGuiTreeNodeFlags flags = ImGuiTreeNodeFlags_None);
  bool CollapsingHeader(const string &in label, bool &inout p_visible, ImGuiTreeNodeFlags flags = ImGuiTreeNodeFlags_None);
  bool ColorButton(const string &in desc_id, const ImVec4 &in col, ImGuiColorEditFlags flags = ImGuiColorEditFlags_None, const ImVec2 &in size = ImVec2(0,0));
  uint ColorConvertFloat4ToU32(const ImVec4 &in in_value);
  void ColorConvertHSVtoRGB(float h, float s, float v, float &inout out_r, float &inout out_g, float &inout out_b);
  void ColorConvertRGBtoHSV(float r, float g, float b, float &inout out_h, float &inout out_s, float &inout out_v);
  ImVec4 ColorConvertU32ToFloat4(uint in_value);
  bool ColorEdit3(const string &in label, ImVec3 &inout col, ImGuiColorEditFlags flags = ImGuiColorEditFlags_None);
  bool ColorEdit4(const string &in label, ImVec4 &inout col, ImGuiColorEditFlags flags = ImGuiColorEditFlags_None);
  bool ColorPicker3(const string &in label, ImVec3 &inout col, ImGuiColorEditFlags flags = ImGuiColorEditFlags_None);
  void Columns(int count = 1, const string &in id = "", bool borders = true);
  bool Combo(const string &in label, int &inout current_item, const string &in items_separated_by_zeros, int popup_max_height_in_items = -1);
  bool DragFloat(const string &in label, float &inout v, float v_speed = 1.0, float v_min = 0.0, float v_max = 0.0, const string &in format = "%.3f", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragFloat2(const string &in label, ImVec2 &inout v, float v_speed = 1.0, float v_min = 0.0, float v_max = 0.0, const string &in format = "%.3f", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragFloat3(const string &in label, ImVec3 &inout v, float v_speed = 1.0, float v_min = 0.0, float v_max = 0.0, const string &in format = "%.3f", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragFloat4(const string &in label, ImVec4 &inout v, float v_speed = 1.0, float v_min = 0.0, float v_max = 0.0, const string &in format = "%.3f", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragFloatRange2(const string &in label, float &inout v_current_min, float &inout v_current_max, float v_speed = 1.0, float v_min = 0.0, float v_max = 0.0, const string &in format = "%.3f", const string &in format_max = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragInt(const string &in label, int &inout v, float v_speed = 1.0, int v_min = 0, int v_max = 0, const string &in format = "%d", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragInt2(const string &in label, ImGuiInt2 &inout v, float v_speed = 1.0, int v_min = 0, int v_max = 0, const string &in format = "%d", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragInt3(const string &in label, ImGuiInt3 &inout v, float v_speed = 1.0, int v_min = 0, int v_max = 0, const string &in format = "%d", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragInt4(const string &in label, ImGuiInt4 &inout v, float v_speed = 1.0, int v_min = 0, int v_max = 0, const string &in format = "%d", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool DragIntRange2(const string &in label, int &inout v_current_min, int &inout v_current_max, float v_speed = 1.0, int v_min = 0, int v_max = 0, const string &in format = "%d", const string &in format_max = "", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  void Dummy(const ImVec2 &in size);
  void End();
  void EndChild();
  void EndCombo();
  void EndDisabled();
  void EndDragDropSource();
  void EndDragDropTarget();
  void EndGroup();
  void EndListBox();
  void EndMainMenuBar();
  void EndMenu();
  void EndMenuBar();
  void EndPopup();
  void EndTabBar();
  void EndTabItem();
  void EndTable();
  void EndTooltip();
  string GetClipboardText();
  uint GetColorU32(ImGuiCol idx, float alpha_mul = 1.0);
  uint GetColorU32(const ImVec4 &in col);
  uint GetColorU32(uint col, float alpha_mul = 1.0);
  int GetColumnIndex();
  float GetColumnOffset(int column_index = -1);
  float GetColumnWidth(int column_index = -1);
  int GetColumnsCount();
  ImVec2 GetContentRegionAvail();
  ImVec2 GetCursorPos();
  float GetCursorPosX();
  float GetCursorPosY();
  ImVec2 GetCursorScreenPos();
  ImVec2 GetCursorStartPos();
  ImFont@ GetFont();
  float GetFontSize();
  ImVec2 GetFontTexUvWhitePixel();
  int GetFrameCount();
  float GetFrameHeight();
  float GetFrameHeightWithSpacing();
  uint GetID(const string &in str_id);
  uint GetID(const string &in str_id_begin, const string &in str_id_end);
  uint GetID(int int_id);
  ImGuiIO@ GetIO();
  ImGuiItemFlags GetItemFlags();
  uint GetItemID();
  ImVec2 GetItemRectMax();
  ImVec2 GetItemRectMin();
  ImVec2 GetItemRectSize();
  string GetKeyName(ImGuiKey key);
  int GetKeyPressedAmount(ImGuiKey key, float repeat_delay, float rate);
  ImGuiViewport@ GetMainViewport();
  int GetMouseClickedCount(ImGuiMouseButton button);
  ImGuiMouseCursor GetMouseCursor();
  ImVec2 GetMouseDragDelta(ImGuiMouseButton button = ImGuiMouseButton_Left, float lock_threshold = -1.0);
  ImVec2 GetMousePos();
  ImVec2 GetMousePosOnOpeningCurrentPopup();
  float GetScrollMaxX();
  float GetScrollMaxY();
  float GetScrollX();
  float GetScrollY();
  ImGuiStorage@ GetStateStorage();
  ImGuiStyle@ GetStyle();
  string GetStyleColorName(ImGuiCol idx);
  float GetTextLineHeight();
  float GetTextLineHeightWithSpacing();
  double GetTime();
  float GetTreeNodeToLabelSpacing();
  string GetVersion();
  ImDrawList@ GetWindowDrawList();
  float GetWindowHeight();
  ImVec2 GetWindowPos();
  ImVec2 GetWindowSize();
  float GetWindowWidth();
  void Indent(float indent_w = 0.0);
  bool InputDouble(const string &in label, double &inout v, double step = 0.0, double step_fast = 0.0, const string &in format = "%.6f", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputFloat(const string &in label, float &inout v, float step = 0.0, float step_fast = 0.0, const string &in format = "%.3f", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputFloat2(const string &in label, ImVec2 &inout v, const string &in format = "%.3f", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputFloat3(const string &in label, ImVec3 &inout v, const string &in format = "%.3f", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputFloat4(const string &in label, ImVec4 &inout v, const string &in format = "%.3f", ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputInt(const string &in label, int &inout v, int step = 1, int step_fast = 100, ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputInt2(const string &in label, ImGuiInt2 &inout v, ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputInt3(const string &in label, ImGuiInt3 &inout v, ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputInt4(const string &in label, ImGuiInt4 &inout v, ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputText(const string &in label, string &inout buf, uint buf_size = 256, ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputTextMultiline(const string &in label, string &inout buf, uint buf_size = 256, const ImVec2 &in size = ImVec2(0,0), ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InputTextWithHint(const string &in label, const string &in hint, string &inout buf, uint buf_size = 256, ImGuiInputTextFlags flags = ImGuiInputTextFlags_None);
  bool InvisibleButton(const string &in str_id, const ImVec2 &in size, ImGuiButtonFlags flags = ImGuiButtonFlags_None);
  bool IsAnyItemActive();
  bool IsAnyItemFocused();
  bool IsAnyItemHovered();
  bool IsAnyMouseDown();
  bool IsItemActivated();
  bool IsItemActive();
  bool IsItemClicked(ImGuiMouseButton mouse_button = ImGuiMouseButton_Left);
  bool IsItemDeactivated();
  bool IsItemDeactivatedAfterEdit();
  bool IsItemEdited();
  bool IsItemFocused();
  bool IsItemHovered(ImGuiHoveredFlags flags = ImGuiHoveredFlags_None);
  bool IsItemToggledOpen();
  bool IsItemToggledSelection();
  bool IsItemVisible();
  bool IsKeyChordPressed(int key_chord);
  bool IsKeyDown(ImGuiKey key);
  bool IsKeyPressed(ImGuiKey key, bool repeat = true);
  bool IsKeyReleased(ImGuiKey key);
  bool IsMouseClicked(ImGuiMouseButton button, bool repeat = false);
  bool IsMouseDoubleClicked(ImGuiMouseButton button);
  bool IsMouseDown(ImGuiMouseButton button);
  bool IsMouseDragging(ImGuiMouseButton button, float lock_threshold = -1.0);
  bool IsMouseHoveringRect(const ImVec2 &in r_min, const ImVec2 &in r_max, bool clip = true);
  bool IsMousePosValid();
  bool IsMouseReleased(ImGuiMouseButton button);
  bool IsMouseReleasedWithDelay(ImGuiMouseButton button, float delay);
  bool IsPopupOpen(const string &in str_id, ImGuiPopupFlags flags = ImGuiPopupFlags_None);
  bool IsRectVisible(const ImVec2 &in size);
  bool IsRectVisible(const ImVec2 &in rect_min, const ImVec2 &in rect_max);
  bool IsWindowAppearing();
  bool IsWindowCollapsed();
  bool IsWindowFocused(ImGuiFocusedFlags flags = ImGuiFocusedFlags_None);
  bool IsWindowHovered(ImGuiHoveredFlags flags = ImGuiHoveredFlags_None);
  void LoadIniSettingsFromDisk(const string &in ini_filename);
  void LoadIniSettingsFromMemory(const string &in ini_data, uint ini_size = 0);
  void LogButtons();
  void LogFinish();
  void LogToClipboard(int auto_open_depth = -1);
  void LogToFile(int auto_open_depth = -1, const string &in filename = "");
  void LogToTTY(int auto_open_depth = -1);
  bool MenuItem(const string &in label, const string &in shortcut = "", bool selected = false, bool enabled = true);
  bool MenuItem(const string &in label, const string &in shortcut, bool &inout p_selected, bool enabled = true);
  void NewLine();
  void NextColumn();
  void OpenPopup(const string &in str_id, ImGuiPopupFlags popup_flags = ImGuiPopupFlags_None);
  void OpenPopup(uint id, ImGuiPopupFlags popup_flags = ImGuiPopupFlags_None);
  void OpenPopupOnItemClick(const string &in str_id = "", ImGuiPopupFlags popup_flags = ImGuiPopupFlags_None);
  void PlotHistogram(const string &in label, float &inout values, int values_count, int values_offset, const string &in overlay_text, float scale_min, float scale_max, const ImVec2 &in graph_size, int stride);
  void PlotLines(const string &in label, float &inout values, int values_count, int values_offset, const string &in overlay_text, float scale_min, float scale_max, const ImVec2 &in graph_size, int stride);
  void PopClipRect();
  void PopFont();
  void PopID();
  void PopItemFlag();
  void PopItemWidth();
  void PopStyleColor(int count = 1);
  void PopStyleVar(int count = 1);
  void PopTextWrapPos();
  void ProgressBar(float fraction, const ImVec2 &in size_arg = ImVec2(-3.402823466e38f,0), const string &in overlay = "");
  void PushClipRect(const ImVec2 &in clip_rect_min, const ImVec2 &in clip_rect_max, bool intersect_with_current_clip_rect);
  void PushFont(ImFont@ font, float font_size_base_unscaled);
  void PushID(const string &in str_id);
  void PushID(const string &in str_id_begin, const string &in str_id_end);
  void PushID(int int_id);
  void PushItemFlag(ImGuiItemFlags option, bool enabled);
  void PushItemWidth(float item_width);
  void PushStyleColor(ImGuiCol idx, uint col);
  void PushStyleColor(ImGuiCol idx, const ImVec4 &in col);
  void PushStyleVar(ImGuiStyleVar idx, float val);
  void PushStyleVar(ImGuiStyleVar idx, const ImVec2 &in val);
  void PushStyleVarX(ImGuiStyleVar idx, float val_x);
  void PushStyleVarY(ImGuiStyleVar idx, float val_y);
  void PushTextWrapPos(float wrap_local_pos_x = 0.0);
  bool RadioButton(const string &in label, bool active);
  bool RadioButton(const string &in label, int &inout v, int v_button);
  void ResetMouseDragDelta(ImGuiMouseButton button = ImGuiMouseButton_Left);
  void SameLine(float offset_from_start_x = 0.0, float spacing = -1.0);
  void SaveIniSettingsToDisk(const string &in ini_filename);
  bool Selectable(const string &in label, bool selected = false, ImGuiSelectableFlags flags = ImGuiSelectableFlags_None, const ImVec2 &in size = ImVec2(0,0));
  bool Selectable(const string &in label, bool &inout p_selected, ImGuiSelectableFlags flags = ImGuiSelectableFlags_None, const ImVec2 &in size = ImVec2(0,0));
  void Separator();
  void SeparatorText(const string &in label);
  void SetClipboardText(const string &in text);
  void SetColorEditOptions(ImGuiColorEditFlags flags);
  void SetColumnOffset(int column_index, float offset_x);
  void SetColumnWidth(int column_index, float width);
  void SetCursorPos(const ImVec2 &in local_pos);
  void SetCursorPosX(float local_x);
  void SetCursorPosY(float local_y);
  void SetCursorScreenPos(const ImVec2 &in pos);
  void SetItemDefaultFocus();
  void SetItemKeyOwner(ImGuiKey key);
  void SetKeyboardFocusHere(int offset = 0);
  void SetMouseCursor(ImGuiMouseCursor cursor_type);
  void SetNavCursorVisible(bool visible);
  void SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard);
  void SetNextFrameWantCaptureMouse(bool want_capture_mouse);
  void SetNextItemAllowOverlap();
  void SetNextItemOpen(bool is_open, ImGuiCond cond = ImGuiCond_None);
  void SetNextItemSelectionUserData(int64 selection_user_data);
  void SetNextItemShortcut(int key_chord, ImGuiInputFlags flags = ImGuiInputFlags_None);
  void SetNextItemStorageID(uint storage_id);
  void SetNextItemWidth(float item_width);
  void SetNextWindowBgAlpha(float alpha);
  void SetNextWindowCollapsed(bool collapsed, ImGuiCond cond = ImGuiCond_None);
  void SetNextWindowContentSize(const ImVec2 &in size);
  void SetNextWindowFocus();
  void SetNextWindowPos(const ImVec2 &in pos, ImGuiCond cond = ImGuiCond_None, const ImVec2 &in pivot = ImVec2(0,0));
  void SetNextWindowScroll(const ImVec2 &in scroll);
  void SetNextWindowSize(const ImVec2 &in size, ImGuiCond cond = ImGuiCond_None);
  void SetNextWindowSizeConstraints(const ImVec2 &in size_min, const ImVec2 &in size_max);
  void SetScrollFromPosX(float local_x, float center_x_ratio = 0.5);
  void SetScrollFromPosY(float local_y, float center_y_ratio = 0.5);
  void SetScrollHereX(float center_x_ratio = 0.5);
  void SetScrollHereY(float center_y_ratio = 0.5);
  void SetScrollX(float scroll_x);
  void SetScrollY(float scroll_y);
  void SetStateStorage(ImGuiStorage@ storage);
  void SetTabItemClosed(const string &in tab_or_docked_window_label);
  void SetWindowCollapsed(bool collapsed, ImGuiCond cond = ImGuiCond_None);
  void SetWindowCollapsed(const string &in name, bool collapsed, ImGuiCond cond = ImGuiCond_None);
  void SetWindowFocus();
  void SetWindowFocus(const string &in name);
  void SetWindowPos(const ImVec2 &in pos, ImGuiCond cond = ImGuiCond_None);
  void SetWindowPos(const string &in name, const ImVec2 &in pos, ImGuiCond cond = ImGuiCond_None);
  void SetWindowSize(const ImVec2 &in size, ImGuiCond cond = ImGuiCond_None);
  void SetWindowSize(const string &in name, const ImVec2 &in size, ImGuiCond cond = ImGuiCond_None);
  bool Shortcut(int key_chord, ImGuiInputFlags flags = ImGuiInputFlags_None);
  void ShowAboutWindow(bool &inout p_open);
  void ShowDemoWindow(bool &inout p_open);
  void ShowFontSelector(const string &in label);
  void ShowIDStackToolWindow(bool &inout p_open);
  void ShowMetricsWindow(bool &inout p_open);
  void ShowStyleEditor(ImGuiStyle@ ref = null);
  bool ShowStyleSelector(const string &in label);
  void ShowUserGuide();
  bool SliderAngle(const string &in label, float &inout v_rad, float v_degrees_min = -360.0, float v_degrees_max = +360.0, const string &in format = "%.0f deg", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool SliderFloat(const string &in label, float &inout v, float v_min, float v_max, const string &in format = "%.3f", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool SliderFloat2(const string &in label, ImVec2 &inout v, float v_min, float v_max, const string &in format = "%.3f", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool SliderFloat3(const string &in label, ImVec3 &inout v, float v_min, float v_max, const string &in format = "%.3f", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool SliderFloat4(const string &in label, ImVec4 &inout v, float v_min, float v_max, const string &in format = "%.3f", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool SliderInt(const string &in label, int &inout v, int v_min, int v_max, const string &in format = "%d", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool SliderInt2(const string &in label, ImGuiInt2 &inout v, int v_min, int v_max, const string &in format = "%d", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool SliderInt3(const string &in label, ImGuiInt3 &inout v, int v_min, int v_max, const string &in format = "%d", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool SliderInt4(const string &in label, ImGuiInt4 &inout v, int v_min, int v_max, const string &in format = "%d", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool SmallButton(const string &in label);
  void Spacing();
  void StyleColorsClassic(ImGuiStyle@ dst = null);
  void StyleColorsDark(ImGuiStyle@ dst = null);
  void StyleColorsLight(ImGuiStyle@ dst = null);
  bool TabItemButton(const string &in label, ImGuiTabItemFlags flags = ImGuiTabItemFlags_None);
  void TableAngledHeadersRow();
  int TableGetColumnCount();
  ImGuiTableColumnFlags TableGetColumnFlags(int column_n = -1);
  int TableGetColumnIndex();
  string TableGetColumnName(int column_n = -1);
  int TableGetHoveredColumn();
  int TableGetRowIndex();
  void TableHeader(const string &in label);
  void TableHeadersRow();
  bool TableNextColumn();
  void TableNextRow(ImGuiTableRowFlags row_flags = ImGuiTableRowFlags_None, float min_row_height = 0.0);
  void TableSetBgColor(ImGuiTableBgTarget target, uint color, int column_n = -1);
  void TableSetColumnEnabled(int column_n, bool v);
  bool TableSetColumnIndex(int column_n);
  void TableSetupColumn(const string &in label, ImGuiTableColumnFlags flags = ImGuiTableColumnFlags_None, float init_width_or_weight = 0.0, uint user_id = 0);
  void TableSetupScrollFreeze(int cols, int rows);
  bool TextLink(const string &in label);
  bool TextLinkOpenURL(const string &in label, const string &in url = "");
  bool TreeNode(const string &in label);
  bool TreeNodeEx(const string &in label, ImGuiTreeNodeFlags flags = ImGuiTreeNodeFlags_None);
  void TreePop();
  void TreePush(const string &in str_id);
  void Unindent(float indent_w = 0.0);
  bool VSliderFloat(const string &in label, const ImVec2 &in size, float &inout v, float v_min, float v_max, const string &in format = "%.3f", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  bool VSliderInt(const string &in label, const ImVec2 &in size, int &inout v, int v_min, int v_max, const string &in format = "%d", ImGuiSliderFlags flags = ImGuiSliderFlags_None);
  void Value(const string &in prefix, bool b);
  void Value(const string &in prefix, int v);
  void Value(const string &in prefix, uint v);
  void Value(const string &in prefix, float v, const string &in float_format = "");
}
