#ifndef BML_BEHAVIOR_TRANSPORT_FIXTURE_API_H
#define BML_BEHAVIOR_TRANSPORT_FIXTURE_API_H

#include "CKTypes.h"

inline const CKGUID BML_BEHAVIOR_TRANSPORT_FIXTURE_GUID(
    0x14c32f0d, 0x56a97b21);

inline const CKGUID BML_BEHAVIOR_TRANSPORT_GRAPH_FIXTURE_GUID(
    0x64b17cd3, 0x0c977ee1);

inline const CKGUID BML_BEHAVIOR_TRANSPORT_PLUGIN_GUID(
    0x31fb0228, 0x64d14aa7);

inline const CKGUID BML_BEHAVIOR_PROVIDER_VALUE_GUID(
    0x6b6d4d65, 0x1ed4607a);

enum BML_BehaviorTransportGraphStage {
    BML_BEHAVIOR_TRANSPORT_GRAPH_NONE = 0,
    BML_BEHAVIOR_TRANSPORT_GRAPH_CREATE,
    BML_BEHAVIOR_TRANSPORT_GRAPH_PARENT_IO,
    BML_BEHAVIOR_TRANSPORT_GRAPH_CHILD_CREATED,
    BML_BEHAVIOR_TRANSPORT_GRAPH_CHILD_INITIALIZED,
    BML_BEHAVIOR_TRANSPORT_GRAPH_CHILD_ADDED,
    BML_BEHAVIOR_TRANSPORT_GRAPH_ENTRY_LINK_CREATED,
    BML_BEHAVIOR_TRANSPORT_GRAPH_ENTRY_SOURCE_SET,
    BML_BEHAVIOR_TRANSPORT_GRAPH_ENTRY_DESTINATION_SET,
    BML_BEHAVIOR_TRANSPORT_GRAPH_ENTRY_LINK_ADDED,
    BML_BEHAVIOR_TRANSPORT_GRAPH_EXIT_LINK_CREATED,
    BML_BEHAVIOR_TRANSPORT_GRAPH_EXIT_SOURCE_SET,
    BML_BEHAVIOR_TRANSPORT_GRAPH_EXIT_DESTINATION_SET,
    BML_BEHAVIOR_TRANSPORT_GRAPH_EXIT_LINK_ADDED,
    BML_BEHAVIOR_TRANSPORT_GRAPH_READY,
};

struct BML_BehaviorTransportGraphTrace {
    int Stage;
    CKERROR Error;
};

using BML_BehaviorTransportReadGraphTrace =
    const BML_BehaviorTransportGraphTrace *(*)();

#endif // BML_BEHAVIOR_TRANSPORT_FIXTURE_API_H
