#ifndef BML_BEHAVIOR_TRANSPORT_FIXTURE_API_H
#define BML_BEHAVIOR_TRANSPORT_FIXTURE_API_H

#include "CKTypes.h"

inline const CKGUID BML_BEHAVIOR_TRANSPORT_FIXTURE_GUID(
    0x14c32f0d, 0x56a97b21);

inline const CKGUID BML_BEHAVIOR_PROVIDER_VALUE_GUID(
    0x6b6d4d65, 0x1ed4607a);

#endif // BML_BEHAVIOR_TRANSPORT_FIXTURE_API_H
