#ifndef BML_BEHAVIOR_TRANSPORT_FIXTURE_API_H
#define BML_BEHAVIOR_TRANSPORT_FIXTURE_API_H

#include "CKTypes.h"

inline const CKGUID BML_BEHAVIOR_TRANSPORT_FIXTURE_GUID(
    0x14c32f0d, 0x56a97b21);

#endif // BML_BEHAVIOR_TRANSPORT_FIXTURE_API_H
