#ifndef BML_IMGUI_API_H
#define BML_IMGUI_API_H

/**
 * @file bml_imgui_api.h
 * @brief Full BML_ImGuiApi struct definition with 46 sub-tables.
 *
 * Auto-generated by tools/generate_bml_imgui_api.py.
 * Does NOT include imgui_internal.h.
 */

#include "imgui.h"

#include "bml_imgui.h"
#include "bml_errors.h"
#include "bml_interface.h"
#include "cimgui.h"

BML_BEGIN_CDECLS

typedef struct BML_ColorApi {
    size_t struct_size;
#include "bml_imgui_color_fields.inc"
} BML_ColorApi;

typedef struct BML_ContextApi {
    size_t struct_size;
#include "bml_imgui_context_fields.inc"
} BML_ContextApi;

typedef struct BML_DrawCmdApi {
    size_t struct_size;
#include "bml_imgui_draw_cmd_fields.inc"
} BML_DrawCmdApi;

typedef struct BML_DrawDataApi {
    size_t struct_size;
#include "bml_imgui_draw_data_fields.inc"
} BML_DrawDataApi;

typedef struct BML_DrawListApi {
    size_t struct_size;
#include "bml_imgui_draw_list_fields.inc"
} BML_DrawListApi;

typedef struct BML_DrawListSplitterApi {
    size_t struct_size;
#include "bml_imgui_draw_list_splitter_fields.inc"
} BML_DrawListSplitterApi;

typedef struct BML_FontApi {
    size_t struct_size;
#include "bml_imgui_font_fields.inc"
} BML_FontApi;

typedef struct BML_FontAtlasApi {
    size_t struct_size;
#include "bml_imgui_font_atlas_fields.inc"
} BML_FontAtlasApi;

typedef struct BML_FontAtlasRectApi {
    size_t struct_size;
#include "bml_imgui_font_atlas_rect_fields.inc"
} BML_FontAtlasRectApi;

typedef struct BML_FontBakedApi {
    size_t struct_size;
#include "bml_imgui_font_baked_fields.inc"
} BML_FontBakedApi;

typedef struct BML_FontConfigApi {
    size_t struct_size;
#include "bml_imgui_font_config_fields.inc"
} BML_FontConfigApi;

typedef struct BML_FontGlyphApi {
    size_t struct_size;
#include "bml_imgui_font_glyph_fields.inc"
} BML_FontGlyphApi;

typedef struct BML_FontGlyphRangesBuilderApi {
    size_t struct_size;
#include "bml_imgui_font_glyph_ranges_builder_fields.inc"
} BML_FontGlyphRangesBuilderApi;

typedef struct BML_InputApi {
    size_t struct_size;
#include "bml_imgui_input_fields.inc"
} BML_InputApi;

typedef struct BML_InputTextCallbackDataApi {
    size_t struct_size;
#include "bml_imgui_input_text_callback_data_fields.inc"
} BML_InputTextCallbackDataApi;

typedef struct BML_IoApi {
    size_t struct_size;
#include "bml_imgui_io_fields.inc"
} BML_IoApi;

typedef struct BML_LayoutApi {
    size_t struct_size;
#include "bml_imgui_layout_fields.inc"
} BML_LayoutApi;

typedef struct BML_ListClipperApi {
    size_t struct_size;
#include "bml_imgui_list_clipper_fields.inc"
} BML_ListClipperApi;

typedef struct BML_MiscApi {
    size_t struct_size;
#include "bml_imgui_misc_fields.inc"
} BML_MiscApi;

typedef struct BML_OnceUponAFrameApi {
    size_t struct_size;
#include "bml_imgui_once_upon_a_frame_fields.inc"
} BML_OnceUponAFrameApi;

typedef struct BML_PayloadApi {
    size_t struct_size;
#include "bml_imgui_payload_fields.inc"
} BML_PayloadApi;

typedef struct BML_PlatformImeDataApi {
    size_t struct_size;
#include "bml_imgui_platform_ime_data_fields.inc"
} BML_PlatformImeDataApi;

typedef struct BML_PlatformIoApi {
    size_t struct_size;
#include "bml_imgui_platform_io_fields.inc"
} BML_PlatformIoApi;

typedef struct BML_SelectionBasicStorageApi {
    size_t struct_size;
#include "bml_imgui_selection_basic_storage_fields.inc"
} BML_SelectionBasicStorageApi;

typedef struct BML_SelectionExternalStorageApi {
    size_t struct_size;
#include "bml_imgui_selection_external_storage_fields.inc"
} BML_SelectionExternalStorageApi;

typedef struct BML_StorageApi {
    size_t struct_size;
#include "bml_imgui_storage_fields.inc"
} BML_StorageApi;

typedef struct BML_StoragePairApi {
    size_t struct_size;
#include "bml_imgui_storage_pair_fields.inc"
} BML_StoragePairApi;

typedef struct BML_StyleApi {
    size_t struct_size;
#include "bml_imgui_style_fields.inc"
} BML_StyleApi;

typedef struct BML_TableColumnSortSpecsApi {
    size_t struct_size;
#include "bml_imgui_table_column_sort_specs_fields.inc"
} BML_TableColumnSortSpecsApi;

typedef struct BML_TableSortSpecsApi {
    size_t struct_size;
#include "bml_imgui_table_sort_specs_fields.inc"
} BML_TableSortSpecsApi;

typedef struct BML_TextBufferApi {
    size_t struct_size;
#include "bml_imgui_text_buffer_fields.inc"
} BML_TextBufferApi;

typedef struct BML_TextFilterApi {
    size_t struct_size;
#include "bml_imgui_text_filter_fields.inc"
} BML_TextFilterApi;

typedef struct BML_TextRangeApi {
    size_t struct_size;
#include "bml_imgui_text_range_fields.inc"
} BML_TextRangeApi;

typedef struct BML_TextureDataApi {
    size_t struct_size;
#include "bml_imgui_texture_data_fields.inc"
} BML_TextureDataApi;

typedef struct BML_TextureRefApi {
    size_t struct_size;
#include "bml_imgui_texture_ref_fields.inc"
} BML_TextureRefApi;

typedef struct BML_Vec2Api {
    size_t struct_size;
#include "bml_imgui_vec2_fields.inc"
} BML_Vec2Api;

typedef struct BML_Vec4Api {
    size_t struct_size;
#include "bml_imgui_vec4_fields.inc"
} BML_Vec4Api;

typedef struct BML_VectorApi {
    size_t struct_size;
#include "bml_imgui_vector_fields.inc"
} BML_VectorApi;

typedef struct BML_ViewportApi {
    size_t struct_size;
#include "bml_imgui_viewport_fields.inc"
} BML_ViewportApi;

typedef struct BML_WidgetButtonApi {
    size_t struct_size;
#include "bml_imgui_widget_button_fields.inc"
} BML_WidgetButtonApi;

typedef struct BML_WidgetPopupApi {
    size_t struct_size;
#include "bml_imgui_widget_popup_fields.inc"
} BML_WidgetPopupApi;

typedef struct BML_WidgetSliderApi {
    size_t struct_size;
#include "bml_imgui_widget_slider_fields.inc"
} BML_WidgetSliderApi;

typedef struct BML_WidgetTableApi {
    size_t struct_size;
#include "bml_imgui_widget_table_fields.inc"
} BML_WidgetTableApi;

typedef struct BML_WidgetTextApi {
    size_t struct_size;
#include "bml_imgui_widget_text_fields.inc"
} BML_WidgetTextApi;

typedef struct BML_WidgetTreeApi {
    size_t struct_size;
#include "bml_imgui_widget_tree_fields.inc"
} BML_WidgetTreeApi;

typedef struct BML_WindowApi {
    size_t struct_size;
#include "bml_imgui_window_fields.inc"
} BML_WindowApi;

typedef struct BML_ImGuiApi {
    BML_InterfaceHeader header;
    const char *imgui_version_utf8;
    const char *cimgui_version_utf8;
    BML_Result (*ValidateMainThreadAccess)(void);
    BML_Result (*ValidateCurrentFrameAccess)(void);
    const BML_ColorApi *color;
    const BML_ContextApi *context;
    const BML_DrawCmdApi *draw_cmd;
    const BML_DrawDataApi *draw_data;
    const BML_DrawListApi *draw_list;
    const BML_DrawListSplitterApi *draw_list_splitter;
    const BML_FontApi *font;
    const BML_FontAtlasApi *font_atlas;
    const BML_FontAtlasRectApi *font_atlas_rect;
    const BML_FontBakedApi *font_baked;
    const BML_FontConfigApi *font_config;
    const BML_FontGlyphApi *font_glyph;
    const BML_FontGlyphRangesBuilderApi *font_glyph_ranges_builder;
    const BML_InputApi *input;
    const BML_InputTextCallbackDataApi *input_text_callback_data;
    const BML_IoApi *io;
    const BML_LayoutApi *layout;
    const BML_ListClipperApi *list_clipper;
    const BML_MiscApi *misc;
    const BML_OnceUponAFrameApi *once_upon_a_frame;
    const BML_PayloadApi *payload;
    const BML_PlatformImeDataApi *platform_ime_data;
    const BML_PlatformIoApi *platform_io;
    const BML_SelectionBasicStorageApi *selection_basic_storage;
    const BML_SelectionExternalStorageApi *selection_external_storage;
    const BML_StorageApi *storage;
    const BML_StoragePairApi *storage_pair;
    const BML_StyleApi *style;
    const BML_TableColumnSortSpecsApi *table_column_sort_specs;
    const BML_TableSortSpecsApi *table_sort_specs;
    const BML_TextBufferApi *text_buffer;
    const BML_TextFilterApi *text_filter;
    const BML_TextRangeApi *text_range;
    const BML_TextureDataApi *texture_data;
    const BML_TextureRefApi *texture_ref;
    const BML_Vec2Api *vec2;
    const BML_Vec4Api *vec4;
    const BML_VectorApi *vector;
    const BML_ViewportApi *viewport;
    const BML_WidgetButtonApi *widget_button;
    const BML_WidgetPopupApi *widget_popup;
    const BML_WidgetSliderApi *widget_slider;
    const BML_WidgetTableApi *widget_table;
    const BML_WidgetTextApi *widget_text;
    const BML_WidgetTreeApi *widget_tree;
    const BML_WindowApi *window;
} BML_ImGuiApi;

BML_END_CDECLS

#endif /* BML_IMGUI_API_H */
