#ifndef BML_EVENT_KINDS_H
#define BML_EVENT_KINDS_H

#include "BML/Defines.h"

/* Stable IDs carried by records from the built-in bml.events stream.  These
 * are data values, not callback signatures or exported C++ types. */
BML_BEGIN_CDECLS

typedef enum BML_EVENT_KIND {
    BML_EVENT_PRE_START_MENU = 1,
    BML_EVENT_POST_START_MENU,
    BML_EVENT_EXIT_GAME,
    BML_EVENT_PRE_LOAD_LEVEL,
    BML_EVENT_POST_LOAD_LEVEL,
    BML_EVENT_START_LEVEL,
    BML_EVENT_PRE_RESET_LEVEL,
    BML_EVENT_POST_RESET_LEVEL,
    BML_EVENT_PAUSE_LEVEL,
    BML_EVENT_UNPAUSE_LEVEL,
    BML_EVENT_PRE_EXIT_LEVEL,
    BML_EVENT_POST_EXIT_LEVEL,
    BML_EVENT_PRE_NEXT_LEVEL,
    BML_EVENT_POST_NEXT_LEVEL,
    BML_EVENT_DEAD,
    BML_EVENT_PRE_END_LEVEL,
    BML_EVENT_POST_END_LEVEL,
    BML_EVENT_COUNTER_ACTIVE,
    BML_EVENT_COUNTER_INACTIVE,
    BML_EVENT_BALL_NAV_ACTIVE,
    BML_EVENT_BALL_NAV_INACTIVE,
    BML_EVENT_CAM_NAV_ACTIVE,
    BML_EVENT_CAM_NAV_INACTIVE,
    BML_EVENT_BALL_OFF,
    BML_EVENT_PRE_CHECKPOINT_REACHED,
    BML_EVENT_POST_CHECKPOINT_REACHED,
    BML_EVENT_LEVEL_FINISH,
    BML_EVENT_GAME_OVER,
    BML_EVENT_EXTRA_POINT,
    BML_EVENT_PRE_SUB_LIFE,
    BML_EVENT_POST_SUB_LIFE,
    BML_EVENT_PRE_LIFE_UP,
    BML_EVENT_POST_LIFE_UP,
    BML_EVENT_LOAD_OBJECT = 64,
    BML_EVENT_LOAD_SCRIPT,
    BML_EVENT_PHYSICALIZE,
    BML_EVENT_UNPHYSICALIZE,
    BML_EVENT_COMMAND_PRE,
    BML_EVENT_COMMAND_POST,
    BML_EVENT_CONFIG_MODIFIED,
    BML_EVENT_CHEAT_CHANGED,
} BML_EVENT_KIND;

BML_END_CDECLS

#endif // BML_EVENT_KINDS_H
