// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by tools/generate_bml_loader.py.
//     Do not edit this file directly. Instead, update the manifest or script.
//
//     Manifest: tools/bml_loader_manifest.json
//     Generated from 162 APIs in 12 groups.
// </auto-generated>
// -----------------------------------------------------------------------------
#ifndef BML_LOADER_AUTOGEN_H
#define BML_LOADER_AUTOGEN_H

/* Total: 162 APIs (26 required, 136 optional) */

#ifdef BML_LOADER_IMPLEMENTATION

/* ========================================================================
 * API Pointer Definitions
 * ======================================================================== */

/* Core APIs (bml_core.h) */
PFN_BML_ContextRetain bmlContextRetain = NULL;
PFN_BML_ContextRelease bmlContextRelease = NULL;
PFN_BML_GetGlobalContext bmlGetGlobalContext = NULL;
PFN_BML_GetRuntimeVersion bmlGetRuntimeVersion = NULL;
PFN_BML_ContextSetUserData bmlContextSetUserData = NULL;
PFN_BML_ContextGetUserData bmlContextGetUserData = NULL;
PFN_BML_RequestCapability bmlRequestCapability = NULL;
PFN_BML_CheckCapability bmlCheckCapability = NULL;
PFN_BML_GetModId bmlGetModId = NULL;
PFN_BML_GetModVersion bmlGetModVersion = NULL;
PFN_BML_RegisterShutdownHook bmlRegisterShutdownHook = NULL;
PFN_BML_CoreGetCaps bmlCoreGetCaps = NULL;
PFN_BML_SetCurrentModule bmlSetCurrentModule = NULL;
PFN_BML_GetCurrentModule bmlGetCurrentModule = NULL;
PFN_BML_GetLoadedModuleCount bmlGetLoadedModuleCount = NULL;
PFN_BML_GetLoadedModuleAt bmlGetLoadedModuleAt = NULL;

/* Logging APIs (bml_logging.h) */
PFN_BML_Log bmlLog = NULL;
PFN_BML_LogVa bmlLogVa = NULL;
PFN_BML_SetLogFilter bmlSetLogFilter = NULL;
PFN_BML_LoggingGetCaps bmlLoggingGetCaps = NULL;

/* Configuration APIs (bml_config.h) */
PFN_BML_ConfigGet bmlConfigGet = NULL;
PFN_BML_ConfigSet bmlConfigSet = NULL;
PFN_BML_ConfigReset bmlConfigReset = NULL;
PFN_BML_ConfigEnumerate bmlConfigEnumerate = NULL;
PFN_BML_ConfigGetCaps bmlConfigGetCaps = NULL;
PFN_BML_ConfigBatchBegin bmlConfigBatchBegin = NULL;
PFN_BML_ConfigBatchSet bmlConfigBatchSet = NULL;
PFN_BML_ConfigBatchCommit bmlConfigBatchCommit = NULL;
PFN_BML_ConfigBatchDiscard bmlConfigBatchDiscard = NULL;

/* IMC APIs (bml_imc.h) */
PFN_BML_ImcGetTopicId bmlImcGetTopicId = NULL;
PFN_BML_ImcGetRpcId bmlImcGetRpcId = NULL;
PFN_BML_ImcPublish bmlImcPublish = NULL;
PFN_BML_ImcPublishEx bmlImcPublishEx = NULL;
PFN_BML_ImcPublishBuffer bmlImcPublishBuffer = NULL;
PFN_BML_ImcSubscribe bmlImcSubscribe = NULL;
PFN_BML_ImcUnsubscribe bmlImcUnsubscribe = NULL;
PFN_BML_ImcSubscriptionIsActive bmlImcSubscriptionIsActive = NULL;
PFN_BML_ImcRegisterRpc bmlImcRegisterRpc = NULL;
PFN_BML_ImcUnregisterRpc bmlImcUnregisterRpc = NULL;
PFN_BML_ImcCallRpc bmlImcCallRpc = NULL;
PFN_BML_ImcFutureAwait bmlImcFutureAwait = NULL;
PFN_BML_ImcFutureGetResult bmlImcFutureGetResult = NULL;
PFN_BML_ImcFutureGetState bmlImcFutureGetState = NULL;
PFN_BML_ImcFutureCancel bmlImcFutureCancel = NULL;
PFN_BML_ImcFutureOnComplete bmlImcFutureOnComplete = NULL;
PFN_BML_ImcFutureRelease bmlImcFutureRelease = NULL;
PFN_BML_ImcPump bmlImcPump = NULL;
PFN_BML_ImcGetCaps bmlImcGetCaps = NULL;
PFN_BML_ImcSubscribeEx bmlImcSubscribeEx = NULL;
PFN_BML_ImcGetSubscriptionStats bmlImcGetSubscriptionStats = NULL;
PFN_BML_ImcPublishMulti bmlImcPublishMulti = NULL;
PFN_BML_ImcGetStats bmlImcGetStats = NULL;
PFN_BML_ImcResetStats bmlImcResetStats = NULL;
PFN_BML_ImcGetTopicInfo bmlImcGetTopicInfo = NULL;
PFN_BML_ImcGetTopicName bmlImcGetTopicName = NULL;

/* Resource APIs (bml_resource.h) */
PFN_BML_HandleCreate bmlHandleCreate = NULL;
PFN_BML_HandleRetain bmlHandleRetain = NULL;
PFN_BML_HandleRelease bmlHandleRelease = NULL;
PFN_BML_HandleValidate bmlHandleValidate = NULL;
PFN_BML_HandleAttachUserData bmlHandleAttachUserData = NULL;
PFN_BML_HandleGetUserData bmlHandleGetUserData = NULL;
PFN_BML_ResourceGetCaps bmlResourceGetCaps = NULL;

/* Extension APIs (bml_extension.h) */
PFN_BML_ExtensionRegister bmlExtensionRegister = NULL;
PFN_BML_ExtensionUnregister bmlExtensionUnregister = NULL;
PFN_BML_ExtensionQuery bmlExtensionQuery = NULL;
PFN_BML_ExtensionLoad bmlExtensionLoad = NULL;
PFN_BML_ExtensionUnload bmlExtensionUnload = NULL;
PFN_BML_ExtensionGetRefCount bmlExtensionGetRefCount = NULL;
PFN_BML_ExtensionEnumerate bmlExtensionEnumerate = NULL;
PFN_BML_ExtensionCount bmlExtensionCount = NULL;
PFN_BML_ExtensionUpdateApi bmlExtensionUpdateApi = NULL;
PFN_BML_ExtensionDeprecate bmlExtensionDeprecate = NULL;
PFN_BML_ExtensionAddListener bmlExtensionAddListener = NULL;
PFN_BML_ExtensionRemoveListener bmlExtensionRemoveListener = NULL;
PFN_BML_ExtensionGetCaps bmlExtensionGetCaps = NULL;

/* Diagnostics APIs (bml_errors.h) */
PFN_BML_GetLastError bmlGetLastError = NULL;
PFN_BML_ClearLastError bmlClearLastError = NULL;
PFN_BML_GetErrorString bmlGetErrorString = NULL;

/* Memory APIs (bml_memory.h) */
PFN_BML_Alloc bmlAlloc = NULL;
PFN_BML_Calloc bmlCalloc = NULL;
PFN_BML_Realloc bmlRealloc = NULL;
PFN_BML_Free bmlFree = NULL;
PFN_BML_AllocAligned bmlAllocAligned = NULL;
PFN_BML_FreeAligned bmlFreeAligned = NULL;
PFN_BML_MemoryPoolCreate bmlMemoryPoolCreate = NULL;
PFN_BML_MemoryPoolAlloc bmlMemoryPoolAlloc = NULL;
PFN_BML_MemoryPoolFree bmlMemoryPoolFree = NULL;
PFN_BML_MemoryPoolDestroy bmlMemoryPoolDestroy = NULL;
PFN_BML_GetMemoryStats bmlGetMemoryStats = NULL;
PFN_BML_MemoryGetCaps bmlMemoryGetCaps = NULL;

/* Synchronization APIs (bml_sync.h) */
PFN_BML_MutexCreate bmlMutexCreate = NULL;
PFN_BML_MutexDestroy bmlMutexDestroy = NULL;
PFN_BML_MutexLock bmlMutexLock = NULL;
PFN_BML_MutexTryLock bmlMutexTryLock = NULL;
PFN_BML_MutexLockTimeout bmlMutexLockTimeout = NULL;
PFN_BML_MutexUnlock bmlMutexUnlock = NULL;
PFN_BML_RwLockCreate bmlRwLockCreate = NULL;
PFN_BML_RwLockDestroy bmlRwLockDestroy = NULL;
PFN_BML_RwLockReadLock bmlRwLockReadLock = NULL;
PFN_BML_RwLockTryReadLock bmlRwLockTryReadLock = NULL;
PFN_BML_RwLockReadLockTimeout bmlRwLockReadLockTimeout = NULL;
PFN_BML_RwLockWriteLock bmlRwLockWriteLock = NULL;
PFN_BML_RwLockTryWriteLock bmlRwLockTryWriteLock = NULL;
PFN_BML_RwLockWriteLockTimeout bmlRwLockWriteLockTimeout = NULL;
PFN_BML_RwLockUnlock bmlRwLockUnlock = NULL;
PFN_BML_AtomicIncrement32 bmlAtomicIncrement32 = NULL;
PFN_BML_AtomicDecrement32 bmlAtomicDecrement32 = NULL;
PFN_BML_AtomicAdd32 bmlAtomicAdd32 = NULL;
PFN_BML_AtomicCompareExchange32 bmlAtomicCompareExchange32 = NULL;
PFN_BML_AtomicExchange32 bmlAtomicExchange32 = NULL;
PFN_BML_AtomicLoadPtr bmlAtomicLoadPtr = NULL;
PFN_BML_AtomicStorePtr bmlAtomicStorePtr = NULL;
PFN_BML_AtomicCompareExchangePtr bmlAtomicCompareExchangePtr = NULL;
PFN_BML_SemaphoreCreate bmlSemaphoreCreate = NULL;
PFN_BML_SemaphoreDestroy bmlSemaphoreDestroy = NULL;
PFN_BML_SemaphoreWait bmlSemaphoreWait = NULL;
PFN_BML_SemaphoreSignal bmlSemaphoreSignal = NULL;
PFN_BML_TlsCreate bmlTlsCreate = NULL;
PFN_BML_TlsDestroy bmlTlsDestroy = NULL;
PFN_BML_TlsGet bmlTlsGet = NULL;
PFN_BML_TlsSet bmlTlsSet = NULL;
PFN_BML_CondVarCreate bmlCondVarCreate = NULL;
PFN_BML_CondVarDestroy bmlCondVarDestroy = NULL;
PFN_BML_CondVarWait bmlCondVarWait = NULL;
PFN_BML_CondVarWaitTimeout bmlCondVarWaitTimeout = NULL;
PFN_BML_CondVarSignal bmlCondVarSignal = NULL;
PFN_BML_CondVarBroadcast bmlCondVarBroadcast = NULL;
PFN_BML_SpinLockCreate bmlSpinLockCreate = NULL;
PFN_BML_SpinLockDestroy bmlSpinLockDestroy = NULL;
PFN_BML_SpinLockLock bmlSpinLockLock = NULL;
PFN_BML_SpinLockTryLock bmlSpinLockTryLock = NULL;
PFN_BML_SpinLockUnlock bmlSpinLockUnlock = NULL;
PFN_BML_SyncGetCaps bmlSyncGetCaps = NULL;

/* Profiling APIs (bml_profiling.h) */
PFN_BML_TraceBegin bmlTraceBegin = NULL;
PFN_BML_TraceEnd bmlTraceEnd = NULL;
PFN_BML_TraceInstant bmlTraceInstant = NULL;
PFN_BML_TraceSetThreadName bmlTraceSetThreadName = NULL;
PFN_BML_TraceCounter bmlTraceCounter = NULL;
PFN_BML_TraceFrameMark bmlTraceFrameMark = NULL;
PFN_BML_GetApiCallCount bmlGetApiCallCount = NULL;
PFN_BML_GetTotalAllocBytes bmlGetTotalAllocBytes = NULL;
PFN_BML_GetTimestampNs bmlGetTimestampNs = NULL;
PFN_BML_GetCpuFrequency bmlGetCpuFrequency = NULL;
PFN_BML_GetProfilerBackend bmlGetProfilerBackend = NULL;
PFN_BML_SetProfilingEnabled bmlSetProfilingEnabled = NULL;
PFN_BML_IsProfilingEnabled bmlIsProfilingEnabled = NULL;
PFN_BML_FlushProfilingData bmlFlushProfilingData = NULL;
PFN_BML_GetProfilingStats bmlGetProfilingStats = NULL;
PFN_BML_ProfilingGetCaps bmlProfilingGetCaps = NULL;

/* API Tracing APIs (bml_api_tracing.h) */
PFN_BML_EnableApiTracing bmlEnableApiTracing = NULL;
PFN_BML_IsApiTracingEnabled bmlIsApiTracingEnabled = NULL;
PFN_BML_SetTraceCallback bmlSetTraceCallback = NULL;
PFN_BML_GetApiStats bmlGetApiStats = NULL;
PFN_BML_EnumerateApiStats bmlEnumerateApiStats = NULL;
PFN_BML_DumpApiStats bmlDumpApiStats = NULL;
PFN_BML_ResetApiStats bmlResetApiStats = NULL;
PFN_BML_ValidateApiId bmlValidateApiId = NULL;

/* Capabilities APIs (bml_capabilities.h) */
PFN_BML_QueryCapabilities bmlQueryCapabilities = NULL;
PFN_BML_HasCapability bmlHasCapability = NULL;
PFN_BML_CheckCompatibility bmlCheckCompatibility = NULL;
PFN_BML_GetApiDescriptor bmlGetApiDescriptor = NULL;
PFN_BML_GetApiDescriptorByName bmlGetApiDescriptorByName = NULL;
PFN_BML_EnumerateApis bmlEnumerateApis = NULL;
PFN_BML_GetApiIntroducedVersion bmlGetApiIntroducedVersion = NULL;

/* ========================================================================
 * Internal Implementation
 * ======================================================================== */

#define BML_ASSIGN_PTR(name) ((void **)&(name))

typedef struct BML_ApiEntry {
    const char *name;
    BML_ApiId id;
    void **target;
    int required;
} BML_ApiEntry;

static void bmlResetApiPointers(void) {
    bmlContextRetain = NULL;
    bmlContextRelease = NULL;
    bmlGetGlobalContext = NULL;
    bmlGetRuntimeVersion = NULL;
    bmlContextSetUserData = NULL;
    bmlContextGetUserData = NULL;
    bmlRequestCapability = NULL;
    bmlCheckCapability = NULL;
    bmlGetModId = NULL;
    bmlGetModVersion = NULL;
    bmlRegisterShutdownHook = NULL;
    bmlCoreGetCaps = NULL;
    bmlSetCurrentModule = NULL;
    bmlGetCurrentModule = NULL;
    bmlGetLoadedModuleCount = NULL;
    bmlGetLoadedModuleAt = NULL;
    bmlLog = NULL;
    bmlLogVa = NULL;
    bmlSetLogFilter = NULL;
    bmlLoggingGetCaps = NULL;
    bmlConfigGet = NULL;
    bmlConfigSet = NULL;
    bmlConfigReset = NULL;
    bmlConfigEnumerate = NULL;
    bmlConfigGetCaps = NULL;
    bmlConfigBatchBegin = NULL;
    bmlConfigBatchSet = NULL;
    bmlConfigBatchCommit = NULL;
    bmlConfigBatchDiscard = NULL;
    bmlImcGetTopicId = NULL;
    bmlImcGetRpcId = NULL;
    bmlImcPublish = NULL;
    bmlImcPublishEx = NULL;
    bmlImcPublishBuffer = NULL;
    bmlImcSubscribe = NULL;
    bmlImcUnsubscribe = NULL;
    bmlImcSubscriptionIsActive = NULL;
    bmlImcRegisterRpc = NULL;
    bmlImcUnregisterRpc = NULL;
    bmlImcCallRpc = NULL;
    bmlImcFutureAwait = NULL;
    bmlImcFutureGetResult = NULL;
    bmlImcFutureGetState = NULL;
    bmlImcFutureCancel = NULL;
    bmlImcFutureOnComplete = NULL;
    bmlImcFutureRelease = NULL;
    bmlImcPump = NULL;
    bmlImcGetCaps = NULL;
    bmlImcSubscribeEx = NULL;
    bmlImcGetSubscriptionStats = NULL;
    bmlImcPublishMulti = NULL;
    bmlImcGetStats = NULL;
    bmlImcResetStats = NULL;
    bmlImcGetTopicInfo = NULL;
    bmlImcGetTopicName = NULL;
    bmlHandleCreate = NULL;
    bmlHandleRetain = NULL;
    bmlHandleRelease = NULL;
    bmlHandleValidate = NULL;
    bmlHandleAttachUserData = NULL;
    bmlHandleGetUserData = NULL;
    bmlResourceGetCaps = NULL;
    bmlExtensionRegister = NULL;
    bmlExtensionUnregister = NULL;
    bmlExtensionQuery = NULL;
    bmlExtensionLoad = NULL;
    bmlExtensionUnload = NULL;
    bmlExtensionGetRefCount = NULL;
    bmlExtensionEnumerate = NULL;
    bmlExtensionCount = NULL;
    bmlExtensionUpdateApi = NULL;
    bmlExtensionDeprecate = NULL;
    bmlExtensionAddListener = NULL;
    bmlExtensionRemoveListener = NULL;
    bmlExtensionGetCaps = NULL;
    bmlGetLastError = NULL;
    bmlClearLastError = NULL;
    bmlGetErrorString = NULL;
    bmlAlloc = NULL;
    bmlCalloc = NULL;
    bmlRealloc = NULL;
    bmlFree = NULL;
    bmlAllocAligned = NULL;
    bmlFreeAligned = NULL;
    bmlMemoryPoolCreate = NULL;
    bmlMemoryPoolAlloc = NULL;
    bmlMemoryPoolFree = NULL;
    bmlMemoryPoolDestroy = NULL;
    bmlGetMemoryStats = NULL;
    bmlMemoryGetCaps = NULL;
    bmlMutexCreate = NULL;
    bmlMutexDestroy = NULL;
    bmlMutexLock = NULL;
    bmlMutexTryLock = NULL;
    bmlMutexLockTimeout = NULL;
    bmlMutexUnlock = NULL;
    bmlRwLockCreate = NULL;
    bmlRwLockDestroy = NULL;
    bmlRwLockReadLock = NULL;
    bmlRwLockTryReadLock = NULL;
    bmlRwLockReadLockTimeout = NULL;
    bmlRwLockWriteLock = NULL;
    bmlRwLockTryWriteLock = NULL;
    bmlRwLockWriteLockTimeout = NULL;
    bmlRwLockUnlock = NULL;
    bmlAtomicIncrement32 = NULL;
    bmlAtomicDecrement32 = NULL;
    bmlAtomicAdd32 = NULL;
    bmlAtomicCompareExchange32 = NULL;
    bmlAtomicExchange32 = NULL;
    bmlAtomicLoadPtr = NULL;
    bmlAtomicStorePtr = NULL;
    bmlAtomicCompareExchangePtr = NULL;
    bmlSemaphoreCreate = NULL;
    bmlSemaphoreDestroy = NULL;
    bmlSemaphoreWait = NULL;
    bmlSemaphoreSignal = NULL;
    bmlTlsCreate = NULL;
    bmlTlsDestroy = NULL;
    bmlTlsGet = NULL;
    bmlTlsSet = NULL;
    bmlCondVarCreate = NULL;
    bmlCondVarDestroy = NULL;
    bmlCondVarWait = NULL;
    bmlCondVarWaitTimeout = NULL;
    bmlCondVarSignal = NULL;
    bmlCondVarBroadcast = NULL;
    bmlSpinLockCreate = NULL;
    bmlSpinLockDestroy = NULL;
    bmlSpinLockLock = NULL;
    bmlSpinLockTryLock = NULL;
    bmlSpinLockUnlock = NULL;
    bmlSyncGetCaps = NULL;
    bmlTraceBegin = NULL;
    bmlTraceEnd = NULL;
    bmlTraceInstant = NULL;
    bmlTraceSetThreadName = NULL;
    bmlTraceCounter = NULL;
    bmlTraceFrameMark = NULL;
    bmlGetApiCallCount = NULL;
    bmlGetTotalAllocBytes = NULL;
    bmlGetTimestampNs = NULL;
    bmlGetCpuFrequency = NULL;
    bmlGetProfilerBackend = NULL;
    bmlSetProfilingEnabled = NULL;
    bmlIsProfilingEnabled = NULL;
    bmlFlushProfilingData = NULL;
    bmlGetProfilingStats = NULL;
    bmlProfilingGetCaps = NULL;
    bmlEnableApiTracing = NULL;
    bmlIsApiTracingEnabled = NULL;
    bmlSetTraceCallback = NULL;
    bmlGetApiStats = NULL;
    bmlEnumerateApiStats = NULL;
    bmlDumpApiStats = NULL;
    bmlResetApiStats = NULL;
    bmlValidateApiId = NULL;
    bmlQueryCapabilities = NULL;
    bmlHasCapability = NULL;
    bmlCheckCompatibility = NULL;
    bmlGetApiDescriptor = NULL;
    bmlGetApiDescriptorByName = NULL;
    bmlEnumerateApis = NULL;
    bmlGetApiIntroducedVersion = NULL;
}

static const BML_ApiEntry kBmlApiEntries[] = {
    /* Core */
    {"bmlContextRetain", BML_API_ID_bmlContextRetain, BML_ASSIGN_PTR(bmlContextRetain), 1},
    {"bmlContextRelease", BML_API_ID_bmlContextRelease, BML_ASSIGN_PTR(bmlContextRelease), 1},
    {"bmlGetGlobalContext", BML_API_ID_bmlGetGlobalContext, BML_ASSIGN_PTR(bmlGetGlobalContext), 1},
    {"bmlGetRuntimeVersion", BML_API_ID_bmlGetRuntimeVersion, BML_ASSIGN_PTR(bmlGetRuntimeVersion), 1},
    {"bmlContextSetUserData", BML_API_ID_bmlContextSetUserData, BML_ASSIGN_PTR(bmlContextSetUserData), 1},
    {"bmlContextGetUserData", BML_API_ID_bmlContextGetUserData, BML_ASSIGN_PTR(bmlContextGetUserData), 1},
    {"bmlRequestCapability", BML_API_ID_bmlRequestCapability, BML_ASSIGN_PTR(bmlRequestCapability), 1},
    {"bmlCheckCapability", BML_API_ID_bmlCheckCapability, BML_ASSIGN_PTR(bmlCheckCapability), 1},
    {"bmlGetModId", BML_API_ID_bmlGetModId, BML_ASSIGN_PTR(bmlGetModId), 1},
    {"bmlGetModVersion", BML_API_ID_bmlGetModVersion, BML_ASSIGN_PTR(bmlGetModVersion), 1},
    {"bmlRegisterShutdownHook", BML_API_ID_bmlRegisterShutdownHook, BML_ASSIGN_PTR(bmlRegisterShutdownHook), 1},
    {"bmlCoreGetCaps", BML_API_ID_bmlCoreGetCaps, BML_ASSIGN_PTR(bmlCoreGetCaps), 1},
    {"bmlSetCurrentModule", BML_API_ID_bmlSetCurrentModule, BML_ASSIGN_PTR(bmlSetCurrentModule), 0},
    {"bmlGetCurrentModule", BML_API_ID_bmlGetCurrentModule, BML_ASSIGN_PTR(bmlGetCurrentModule), 0},
    {"bmlGetLoadedModuleCount", BML_API_ID_bmlGetLoadedModuleCount, BML_ASSIGN_PTR(bmlGetLoadedModuleCount), 0},
    {"bmlGetLoadedModuleAt", BML_API_ID_bmlGetLoadedModuleAt, BML_ASSIGN_PTR(bmlGetLoadedModuleAt), 0},
    /* Logging */
    {"bmlLog", BML_API_ID_bmlLog, BML_ASSIGN_PTR(bmlLog), 1},
    {"bmlLogVa", BML_API_ID_bmlLogVa, BML_ASSIGN_PTR(bmlLogVa), 0},
    {"bmlSetLogFilter", BML_API_ID_bmlSetLogFilter, BML_ASSIGN_PTR(bmlSetLogFilter), 0},
    {"bmlLoggingGetCaps", BML_API_ID_bmlLoggingGetCaps, BML_ASSIGN_PTR(bmlLoggingGetCaps), 1},
    /* Configuration */
    {"bmlConfigGet", BML_API_ID_bmlConfigGet, BML_ASSIGN_PTR(bmlConfigGet), 1},
    {"bmlConfigSet", BML_API_ID_bmlConfigSet, BML_ASSIGN_PTR(bmlConfigSet), 1},
    {"bmlConfigReset", BML_API_ID_bmlConfigReset, BML_ASSIGN_PTR(bmlConfigReset), 0},
    {"bmlConfigEnumerate", BML_API_ID_bmlConfigEnumerate, BML_ASSIGN_PTR(bmlConfigEnumerate), 0},
    {"bmlConfigGetCaps", BML_API_ID_bmlConfigGetCaps, BML_ASSIGN_PTR(bmlConfigGetCaps), 1},
    {"bmlConfigBatchBegin", BML_API_ID_bmlConfigBatchBegin, BML_ASSIGN_PTR(bmlConfigBatchBegin), 0},
    {"bmlConfigBatchSet", BML_API_ID_bmlConfigBatchSet, BML_ASSIGN_PTR(bmlConfigBatchSet), 0},
    {"bmlConfigBatchCommit", BML_API_ID_bmlConfigBatchCommit, BML_ASSIGN_PTR(bmlConfigBatchCommit), 0},
    {"bmlConfigBatchDiscard", BML_API_ID_bmlConfigBatchDiscard, BML_ASSIGN_PTR(bmlConfigBatchDiscard), 0},
    /* IMC */
    {"bmlImcGetTopicId", BML_API_ID_bmlImcGetTopicId, BML_ASSIGN_PTR(bmlImcGetTopicId), 1},
    {"bmlImcGetRpcId", BML_API_ID_bmlImcGetRpcId, BML_ASSIGN_PTR(bmlImcGetRpcId), 0},
    {"bmlImcPublish", BML_API_ID_bmlImcPublish, BML_ASSIGN_PTR(bmlImcPublish), 1},
    {"bmlImcPublishEx", BML_API_ID_bmlImcPublishEx, BML_ASSIGN_PTR(bmlImcPublishEx), 0},
    {"bmlImcPublishBuffer", BML_API_ID_bmlImcPublishBuffer, BML_ASSIGN_PTR(bmlImcPublishBuffer), 0},
    {"bmlImcSubscribe", BML_API_ID_bmlImcSubscribe, BML_ASSIGN_PTR(bmlImcSubscribe), 1},
    {"bmlImcUnsubscribe", BML_API_ID_bmlImcUnsubscribe, BML_ASSIGN_PTR(bmlImcUnsubscribe), 1},
    {"bmlImcSubscriptionIsActive", BML_API_ID_bmlImcSubscriptionIsActive, BML_ASSIGN_PTR(bmlImcSubscriptionIsActive), 0},
    {"bmlImcRegisterRpc", BML_API_ID_bmlImcRegisterRpc, BML_ASSIGN_PTR(bmlImcRegisterRpc), 0},
    {"bmlImcUnregisterRpc", BML_API_ID_bmlImcUnregisterRpc, BML_ASSIGN_PTR(bmlImcUnregisterRpc), 0},
    {"bmlImcCallRpc", BML_API_ID_bmlImcCallRpc, BML_ASSIGN_PTR(bmlImcCallRpc), 0},
    {"bmlImcFutureAwait", BML_API_ID_bmlImcFutureAwait, BML_ASSIGN_PTR(bmlImcFutureAwait), 0},
    {"bmlImcFutureGetResult", BML_API_ID_bmlImcFutureGetResult, BML_ASSIGN_PTR(bmlImcFutureGetResult), 0},
    {"bmlImcFutureGetState", BML_API_ID_bmlImcFutureGetState, BML_ASSIGN_PTR(bmlImcFutureGetState), 0},
    {"bmlImcFutureCancel", BML_API_ID_bmlImcFutureCancel, BML_ASSIGN_PTR(bmlImcFutureCancel), 0},
    {"bmlImcFutureOnComplete", BML_API_ID_bmlImcFutureOnComplete, BML_ASSIGN_PTR(bmlImcFutureOnComplete), 0},
    {"bmlImcFutureRelease", BML_API_ID_bmlImcFutureRelease, BML_ASSIGN_PTR(bmlImcFutureRelease), 0},
    {"bmlImcPump", BML_API_ID_bmlImcPump, BML_ASSIGN_PTR(bmlImcPump), 0},
    {"bmlImcGetCaps", BML_API_ID_bmlImcGetCaps, BML_ASSIGN_PTR(bmlImcGetCaps), 1},
    {"bmlImcSubscribeEx", BML_API_ID_bmlImcSubscribeEx, BML_ASSIGN_PTR(bmlImcSubscribeEx), 0},
    {"bmlImcGetSubscriptionStats", BML_API_ID_bmlImcGetSubscriptionStats, BML_ASSIGN_PTR(bmlImcGetSubscriptionStats), 0},
    {"bmlImcPublishMulti", BML_API_ID_bmlImcPublishMulti, BML_ASSIGN_PTR(bmlImcPublishMulti), 0},
    {"bmlImcGetStats", BML_API_ID_bmlImcGetStats, BML_ASSIGN_PTR(bmlImcGetStats), 0},
    {"bmlImcResetStats", BML_API_ID_bmlImcResetStats, BML_ASSIGN_PTR(bmlImcResetStats), 0},
    {"bmlImcGetTopicInfo", BML_API_ID_bmlImcGetTopicInfo, BML_ASSIGN_PTR(bmlImcGetTopicInfo), 0},
    {"bmlImcGetTopicName", BML_API_ID_bmlImcGetTopicName, BML_ASSIGN_PTR(bmlImcGetTopicName), 0},
    /* Resource */
    {"bmlHandleCreate", BML_API_ID_bmlHandleCreate, BML_ASSIGN_PTR(bmlHandleCreate), 0},
    {"bmlHandleRetain", BML_API_ID_bmlHandleRetain, BML_ASSIGN_PTR(bmlHandleRetain), 0},
    {"bmlHandleRelease", BML_API_ID_bmlHandleRelease, BML_ASSIGN_PTR(bmlHandleRelease), 0},
    {"bmlHandleValidate", BML_API_ID_bmlHandleValidate, BML_ASSIGN_PTR(bmlHandleValidate), 0},
    {"bmlHandleAttachUserData", BML_API_ID_bmlHandleAttachUserData, BML_ASSIGN_PTR(bmlHandleAttachUserData), 0},
    {"bmlHandleGetUserData", BML_API_ID_bmlHandleGetUserData, BML_ASSIGN_PTR(bmlHandleGetUserData), 0},
    {"bmlResourceGetCaps", BML_API_ID_bmlResourceGetCaps, BML_ASSIGN_PTR(bmlResourceGetCaps), 0},
    /* Extension */
    {"bmlExtensionRegister", BML_API_ID_bmlExtensionRegister, BML_ASSIGN_PTR(bmlExtensionRegister), 1},
    {"bmlExtensionUnregister", BML_API_ID_bmlExtensionUnregister, BML_ASSIGN_PTR(bmlExtensionUnregister), 0},
    {"bmlExtensionQuery", BML_API_ID_bmlExtensionQuery, BML_ASSIGN_PTR(bmlExtensionQuery), 1},
    {"bmlExtensionLoad", BML_API_ID_bmlExtensionLoad, BML_ASSIGN_PTR(bmlExtensionLoad), 1},
    {"bmlExtensionUnload", BML_API_ID_bmlExtensionUnload, BML_ASSIGN_PTR(bmlExtensionUnload), 0},
    {"bmlExtensionGetRefCount", BML_API_ID_bmlExtensionGetRefCount, BML_ASSIGN_PTR(bmlExtensionGetRefCount), 0},
    {"bmlExtensionEnumerate", BML_API_ID_bmlExtensionEnumerate, BML_ASSIGN_PTR(bmlExtensionEnumerate), 0},
    {"bmlExtensionCount", BML_API_ID_bmlExtensionCount, BML_ASSIGN_PTR(bmlExtensionCount), 0},
    {"bmlExtensionUpdateApi", BML_API_ID_bmlExtensionUpdateApi, BML_ASSIGN_PTR(bmlExtensionUpdateApi), 0},
    {"bmlExtensionDeprecate", BML_API_ID_bmlExtensionDeprecate, BML_ASSIGN_PTR(bmlExtensionDeprecate), 0},
    {"bmlExtensionAddListener", BML_API_ID_bmlExtensionAddListener, BML_ASSIGN_PTR(bmlExtensionAddListener), 0},
    {"bmlExtensionRemoveListener", BML_API_ID_bmlExtensionRemoveListener, BML_ASSIGN_PTR(bmlExtensionRemoveListener), 0},
    {"bmlExtensionGetCaps", BML_API_ID_bmlExtensionGetCaps, BML_ASSIGN_PTR(bmlExtensionGetCaps), 1},
    /* Diagnostics */
    {"bmlGetLastError", BML_API_ID_bmlGetLastError, BML_ASSIGN_PTR(bmlGetLastError), 0},
    {"bmlClearLastError", BML_API_ID_bmlClearLastError, BML_ASSIGN_PTR(bmlClearLastError), 0},
    {"bmlGetErrorString", BML_API_ID_bmlGetErrorString, BML_ASSIGN_PTR(bmlGetErrorString), 0},
    /* Memory */
    {"bmlAlloc", BML_API_ID_bmlAlloc, BML_ASSIGN_PTR(bmlAlloc), 0},
    {"bmlCalloc", BML_API_ID_bmlCalloc, BML_ASSIGN_PTR(bmlCalloc), 0},
    {"bmlRealloc", BML_API_ID_bmlRealloc, BML_ASSIGN_PTR(bmlRealloc), 0},
    {"bmlFree", BML_API_ID_bmlFree, BML_ASSIGN_PTR(bmlFree), 0},
    {"bmlAllocAligned", BML_API_ID_bmlAllocAligned, BML_ASSIGN_PTR(bmlAllocAligned), 0},
    {"bmlFreeAligned", BML_API_ID_bmlFreeAligned, BML_ASSIGN_PTR(bmlFreeAligned), 0},
    {"bmlMemoryPoolCreate", BML_API_ID_bmlMemoryPoolCreate, BML_ASSIGN_PTR(bmlMemoryPoolCreate), 0},
    {"bmlMemoryPoolAlloc", BML_API_ID_bmlMemoryPoolAlloc, BML_ASSIGN_PTR(bmlMemoryPoolAlloc), 0},
    {"bmlMemoryPoolFree", BML_API_ID_bmlMemoryPoolFree, BML_ASSIGN_PTR(bmlMemoryPoolFree), 0},
    {"bmlMemoryPoolDestroy", BML_API_ID_bmlMemoryPoolDestroy, BML_ASSIGN_PTR(bmlMemoryPoolDestroy), 0},
    {"bmlGetMemoryStats", BML_API_ID_bmlGetMemoryStats, BML_ASSIGN_PTR(bmlGetMemoryStats), 0},
    {"bmlMemoryGetCaps", BML_API_ID_bmlMemoryGetCaps, BML_ASSIGN_PTR(bmlMemoryGetCaps), 0},
    /* Synchronization */
    {"bmlMutexCreate", BML_API_ID_bmlMutexCreate, BML_ASSIGN_PTR(bmlMutexCreate), 0},
    {"bmlMutexDestroy", BML_API_ID_bmlMutexDestroy, BML_ASSIGN_PTR(bmlMutexDestroy), 0},
    {"bmlMutexLock", BML_API_ID_bmlMutexLock, BML_ASSIGN_PTR(bmlMutexLock), 0},
    {"bmlMutexTryLock", BML_API_ID_bmlMutexTryLock, BML_ASSIGN_PTR(bmlMutexTryLock), 0},
    {"bmlMutexLockTimeout", BML_API_ID_bmlMutexLockTimeout, BML_ASSIGN_PTR(bmlMutexLockTimeout), 0},
    {"bmlMutexUnlock", BML_API_ID_bmlMutexUnlock, BML_ASSIGN_PTR(bmlMutexUnlock), 0},
    {"bmlRwLockCreate", BML_API_ID_bmlRwLockCreate, BML_ASSIGN_PTR(bmlRwLockCreate), 0},
    {"bmlRwLockDestroy", BML_API_ID_bmlRwLockDestroy, BML_ASSIGN_PTR(bmlRwLockDestroy), 0},
    {"bmlRwLockReadLock", BML_API_ID_bmlRwLockReadLock, BML_ASSIGN_PTR(bmlRwLockReadLock), 0},
    {"bmlRwLockTryReadLock", BML_API_ID_bmlRwLockTryReadLock, BML_ASSIGN_PTR(bmlRwLockTryReadLock), 0},
    {"bmlRwLockReadLockTimeout", BML_API_ID_bmlRwLockReadLockTimeout, BML_ASSIGN_PTR(bmlRwLockReadLockTimeout), 0},
    {"bmlRwLockWriteLock", BML_API_ID_bmlRwLockWriteLock, BML_ASSIGN_PTR(bmlRwLockWriteLock), 0},
    {"bmlRwLockTryWriteLock", BML_API_ID_bmlRwLockTryWriteLock, BML_ASSIGN_PTR(bmlRwLockTryWriteLock), 0},
    {"bmlRwLockWriteLockTimeout", BML_API_ID_bmlRwLockWriteLockTimeout, BML_ASSIGN_PTR(bmlRwLockWriteLockTimeout), 0},
    {"bmlRwLockUnlock", BML_API_ID_bmlRwLockUnlock, BML_ASSIGN_PTR(bmlRwLockUnlock), 0},
    {"bmlAtomicIncrement32", BML_API_ID_bmlAtomicIncrement32, BML_ASSIGN_PTR(bmlAtomicIncrement32), 0},
    {"bmlAtomicDecrement32", BML_API_ID_bmlAtomicDecrement32, BML_ASSIGN_PTR(bmlAtomicDecrement32), 0},
    {"bmlAtomicAdd32", BML_API_ID_bmlAtomicAdd32, BML_ASSIGN_PTR(bmlAtomicAdd32), 0},
    {"bmlAtomicCompareExchange32", BML_API_ID_bmlAtomicCompareExchange32, BML_ASSIGN_PTR(bmlAtomicCompareExchange32), 0},
    {"bmlAtomicExchange32", BML_API_ID_bmlAtomicExchange32, BML_ASSIGN_PTR(bmlAtomicExchange32), 0},
    {"bmlAtomicLoadPtr", BML_API_ID_bmlAtomicLoadPtr, BML_ASSIGN_PTR(bmlAtomicLoadPtr), 0},
    {"bmlAtomicStorePtr", BML_API_ID_bmlAtomicStorePtr, BML_ASSIGN_PTR(bmlAtomicStorePtr), 0},
    {"bmlAtomicCompareExchangePtr", BML_API_ID_bmlAtomicCompareExchangePtr, BML_ASSIGN_PTR(bmlAtomicCompareExchangePtr), 0},
    {"bmlSemaphoreCreate", BML_API_ID_bmlSemaphoreCreate, BML_ASSIGN_PTR(bmlSemaphoreCreate), 0},
    {"bmlSemaphoreDestroy", BML_API_ID_bmlSemaphoreDestroy, BML_ASSIGN_PTR(bmlSemaphoreDestroy), 0},
    {"bmlSemaphoreWait", BML_API_ID_bmlSemaphoreWait, BML_ASSIGN_PTR(bmlSemaphoreWait), 0},
    {"bmlSemaphoreSignal", BML_API_ID_bmlSemaphoreSignal, BML_ASSIGN_PTR(bmlSemaphoreSignal), 0},
    {"bmlTlsCreate", BML_API_ID_bmlTlsCreate, BML_ASSIGN_PTR(bmlTlsCreate), 0},
    {"bmlTlsDestroy", BML_API_ID_bmlTlsDestroy, BML_ASSIGN_PTR(bmlTlsDestroy), 0},
    {"bmlTlsGet", BML_API_ID_bmlTlsGet, BML_ASSIGN_PTR(bmlTlsGet), 0},
    {"bmlTlsSet", BML_API_ID_bmlTlsSet, BML_ASSIGN_PTR(bmlTlsSet), 0},
    {"bmlCondVarCreate", BML_API_ID_bmlCondVarCreate, BML_ASSIGN_PTR(bmlCondVarCreate), 0},
    {"bmlCondVarDestroy", BML_API_ID_bmlCondVarDestroy, BML_ASSIGN_PTR(bmlCondVarDestroy), 0},
    {"bmlCondVarWait", BML_API_ID_bmlCondVarWait, BML_ASSIGN_PTR(bmlCondVarWait), 0},
    {"bmlCondVarWaitTimeout", BML_API_ID_bmlCondVarWaitTimeout, BML_ASSIGN_PTR(bmlCondVarWaitTimeout), 0},
    {"bmlCondVarSignal", BML_API_ID_bmlCondVarSignal, BML_ASSIGN_PTR(bmlCondVarSignal), 0},
    {"bmlCondVarBroadcast", BML_API_ID_bmlCondVarBroadcast, BML_ASSIGN_PTR(bmlCondVarBroadcast), 0},
    {"bmlSpinLockCreate", BML_API_ID_bmlSpinLockCreate, BML_ASSIGN_PTR(bmlSpinLockCreate), 0},
    {"bmlSpinLockDestroy", BML_API_ID_bmlSpinLockDestroy, BML_ASSIGN_PTR(bmlSpinLockDestroy), 0},
    {"bmlSpinLockLock", BML_API_ID_bmlSpinLockLock, BML_ASSIGN_PTR(bmlSpinLockLock), 0},
    {"bmlSpinLockTryLock", BML_API_ID_bmlSpinLockTryLock, BML_ASSIGN_PTR(bmlSpinLockTryLock), 0},
    {"bmlSpinLockUnlock", BML_API_ID_bmlSpinLockUnlock, BML_ASSIGN_PTR(bmlSpinLockUnlock), 0},
    {"bmlSyncGetCaps", BML_API_ID_bmlSyncGetCaps, BML_ASSIGN_PTR(bmlSyncGetCaps), 0},
    /* Profiling */
    {"bmlTraceBegin", BML_API_ID_bmlTraceBegin, BML_ASSIGN_PTR(bmlTraceBegin), 0},
    {"bmlTraceEnd", BML_API_ID_bmlTraceEnd, BML_ASSIGN_PTR(bmlTraceEnd), 0},
    {"bmlTraceInstant", BML_API_ID_bmlTraceInstant, BML_ASSIGN_PTR(bmlTraceInstant), 0},
    {"bmlTraceSetThreadName", BML_API_ID_bmlTraceSetThreadName, BML_ASSIGN_PTR(bmlTraceSetThreadName), 0},
    {"bmlTraceCounter", BML_API_ID_bmlTraceCounter, BML_ASSIGN_PTR(bmlTraceCounter), 0},
    {"bmlTraceFrameMark", BML_API_ID_bmlTraceFrameMark, BML_ASSIGN_PTR(bmlTraceFrameMark), 0},
    {"bmlGetApiCallCount", BML_API_ID_bmlGetApiCallCount, BML_ASSIGN_PTR(bmlGetApiCallCount), 0},
    {"bmlGetTotalAllocBytes", BML_API_ID_bmlGetTotalAllocBytes, BML_ASSIGN_PTR(bmlGetTotalAllocBytes), 0},
    {"bmlGetTimestampNs", BML_API_ID_bmlGetTimestampNs, BML_ASSIGN_PTR(bmlGetTimestampNs), 0},
    {"bmlGetCpuFrequency", BML_API_ID_bmlGetCpuFrequency, BML_ASSIGN_PTR(bmlGetCpuFrequency), 0},
    {"bmlGetProfilerBackend", BML_API_ID_bmlGetProfilerBackend, BML_ASSIGN_PTR(bmlGetProfilerBackend), 0},
    {"bmlSetProfilingEnabled", BML_API_ID_bmlSetProfilingEnabled, BML_ASSIGN_PTR(bmlSetProfilingEnabled), 0},
    {"bmlIsProfilingEnabled", BML_API_ID_bmlIsProfilingEnabled, BML_ASSIGN_PTR(bmlIsProfilingEnabled), 0},
    {"bmlFlushProfilingData", BML_API_ID_bmlFlushProfilingData, BML_ASSIGN_PTR(bmlFlushProfilingData), 0},
    {"bmlGetProfilingStats", BML_API_ID_bmlGetProfilingStats, BML_ASSIGN_PTR(bmlGetProfilingStats), 0},
    {"bmlProfilingGetCaps", BML_API_ID_bmlProfilingGetCaps, BML_ASSIGN_PTR(bmlProfilingGetCaps), 0},
    /* API Tracing */
    {"bmlEnableApiTracing", BML_API_ID_bmlEnableApiTracing, BML_ASSIGN_PTR(bmlEnableApiTracing), 0},
    {"bmlIsApiTracingEnabled", BML_API_ID_bmlIsApiTracingEnabled, BML_ASSIGN_PTR(bmlIsApiTracingEnabled), 0},
    {"bmlSetTraceCallback", BML_API_ID_bmlSetTraceCallback, BML_ASSIGN_PTR(bmlSetTraceCallback), 0},
    {"bmlGetApiStats", BML_API_ID_bmlGetApiStats, BML_ASSIGN_PTR(bmlGetApiStats), 0},
    {"bmlEnumerateApiStats", BML_API_ID_bmlEnumerateApiStats, BML_ASSIGN_PTR(bmlEnumerateApiStats), 0},
    {"bmlDumpApiStats", BML_API_ID_bmlDumpApiStats, BML_ASSIGN_PTR(bmlDumpApiStats), 0},
    {"bmlResetApiStats", BML_API_ID_bmlResetApiStats, BML_ASSIGN_PTR(bmlResetApiStats), 0},
    {"bmlValidateApiId", BML_API_ID_bmlValidateApiId, BML_ASSIGN_PTR(bmlValidateApiId), 0},
    /* Capabilities */
    {"bmlQueryCapabilities", BML_API_ID_bmlQueryCapabilities, BML_ASSIGN_PTR(bmlQueryCapabilities), 0},
    {"bmlHasCapability", BML_API_ID_bmlHasCapability, BML_ASSIGN_PTR(bmlHasCapability), 0},
    {"bmlCheckCompatibility", BML_API_ID_bmlCheckCompatibility, BML_ASSIGN_PTR(bmlCheckCompatibility), 0},
    {"bmlGetApiDescriptor", BML_API_ID_bmlGetApiDescriptor, BML_ASSIGN_PTR(bmlGetApiDescriptor), 0},
    {"bmlGetApiDescriptorByName", BML_API_ID_bmlGetApiDescriptorByName, BML_ASSIGN_PTR(bmlGetApiDescriptorByName), 0},
    {"bmlEnumerateApis", BML_API_ID_bmlEnumerateApis, BML_ASSIGN_PTR(bmlEnumerateApis), 0},
    {"bmlGetApiIntroducedVersion", BML_API_ID_bmlGetApiIntroducedVersion, BML_ASSIGN_PTR(bmlGetApiIntroducedVersion), 0},
};

/* ========================================================================
 * Public Loader Functions
 * ======================================================================== */

BML_Result bmlLoadAPI(PFN_BML_GetProcAddress get_proc,
                      PFN_BML_GetProcAddressById get_proc_by_id) {
    size_t i;

    if (!get_proc)
        return BML_RESULT_INVALID_ARGUMENT;

    for (i = 0; i < (sizeof(kBmlApiEntries) / sizeof(kBmlApiEntries[0])); ++i) {
        void *proc = NULL;
        if (get_proc_by_id)
            proc = get_proc_by_id(kBmlApiEntries[i].id);
        if (!proc)
            proc = get_proc(kBmlApiEntries[i].name);
        if (!proc) {
            if (kBmlApiEntries[i].required) {
                bmlUnloadAPI();
                return BML_RESULT_NOT_FOUND;
            }
            continue;
        }
        *kBmlApiEntries[i].target = proc;
    }

    return BML_RESULT_OK;
}

void bmlUnloadAPI(void) {
    bmlResetApiPointers();
}

BML_Bool bmlIsApiLoaded(void) {
    return (bmlContextRetain != NULL) ? BML_TRUE : BML_FALSE;
}

size_t bmlGetApiCount(void) {
    return 162;
}

size_t bmlGetRequiredApiCount(void) {
    return 26;
}

#undef BML_ASSIGN_PTR

#endif /* BML_LOADER_IMPLEMENTATION */

#endif /* BML_LOADER_AUTOGEN_H */
