name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    env:
      VIRTOOLS_SDK_PATH: ${{github.workspace}}/Virtools-SDK-2.1
      PROJECT_NAME: BallanceModLoaderPlus
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Checkout Virtools SDK
        uses: actions/checkout@v4
        with:
          repository: doyaGu/Virtools-SDK-2.1
          path: ${{env.VIRTOOLS_SDK_PATH}}
        
      - uses: lukka/get-cmake@latest
  
      - uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
        with:
          arch: x86
        
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A Win32
  
      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install --config ${{env.BUILD_TYPE}}
        
      - name: Release Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{env.PROJECT_NAME}}
          path: ${{github.workspace}}/install
