name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      VIRTOOLS_SDK_PATH: ${{ github.workspace }}/Virtools-SDK-2.1
      PROJECT_NAME: BallanceModLoaderPlus
      
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checkout Virtools SDK
      uses: actions/checkout@v4
      with:
        repository: doyaGu/Virtools-SDK-2.1
        path: ${{ env.VIRTOOLS_SDK_PATH }}

    - name: Get current branch and commit hash
      shell: bash
      run: |
        echo "GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
        echo "GIT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
      with:
        arch: x86
      
    - name: Configure CMake for Release version
      run: cmake -B ${{ github.workspace }}/build-release -DCMAKE_BUILD_TYPE=Release -A Win32

    - name: Configure CMake for Debug version
      run: cmake -B ${{ github.workspace }}/build-debug -DCMAKE_BUILD_TYPE=Debug -A Win32
  
    - name: Build Release version
      # Build your program with the given configuration
      run: cmake --build ${{ github.workspace }}/build-release --config Release

    - name: Build Debug version
      # Build your program with the given configuration
      run: cmake --build ${{ github.workspace }}/build-debug --config Debug

    - name: Test Release version
      working-directory: ${{ github.workspace }}/build-release
      run: ctest -C Release

    - name: Test Debug version
      working-directory: ${{ github.workspace }}/build-debug
      run: ctest -C Debug

    - name: Install Release version
      run: cmake --install ${{ github.workspace }}/build-release --prefix ${{ github.workspace }}/dist-release --config Release

    - name: Install Debug version
      run: cmake --install ${{ github.workspace }}/build-debug --prefix ${{ github.workspace }}/dist-debug --config Debug
      
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{env.PROJECT_NAME}}-${{env.GIT_SHA}}-Release
        path: ${{github.workspace}}/dist-release

    - name: Upload Debug Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{env.PROJECT_NAME}}-${{env.GIT_SHA}}-Debug
        path: ${{github.workspace}}/dist-debug
